// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: delivery_methods.sql

package postgresqlc

import (
	"context"
)

const deliveryMethod = `-- name: DeliveryMethod :one
SELECT id, units, name, description
FROM delivery_methods
WHERE name = $1
`

func (q *Queries) DeliveryMethod(ctx context.Context, name string) (DeliveryMethod, error) {
	row := q.db.QueryRow(ctx, deliveryMethod, name)
	var i DeliveryMethod
	err := row.Scan(
		&i.ID,
		&i.Units,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const deliveryMethods = `-- name: DeliveryMethods :many
/*
 * Delivery Method
 */
SELECT id, units, name, description
FROM delivery_methods
`

// Language: postgresql
func (q *Queries) DeliveryMethods(ctx context.Context) ([]DeliveryMethod, error) {
	rows, err := q.db.Query(ctx, deliveryMethods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryMethod
	for rows.Next() {
		var i DeliveryMethod
		if err := rows.Scan(
			&i.ID,
			&i.Units,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
