// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dosage.sql

package postgresqlc

import (
	"context"

	userservice "e2clicker.app/services/user"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDosageSchedule = `-- name: DeleteDosageSchedule :exec
DELETE FROM dosage_schedule
WHERE user_secret = $1
`

func (q *Queries) DeleteDosageSchedule(ctx context.Context, userSecret userservice.Secret) error {
	_, err := q.db.Exec(ctx, deleteDosageSchedule, userSecret)
	return err
}

const dosageSchedule = `-- name: DosageSchedule :one
/*
 * Dosage and dosage-related
 */
SELECT user_secret, delivery_method, dose, interval, concurrence, reminder_recurrence
FROM dosage_schedule
WHERE user_secret = $1
`

func (q *Queries) DosageSchedule(ctx context.Context, userSecret userservice.Secret) (DosageSchedule, error) {
	row := q.db.QueryRow(ctx, dosageSchedule, userSecret)
	var i DosageSchedule
	err := row.Scan(
		&i.UserSecret,
		&i.DeliveryMethod,
		&i.Dose,
		&i.Interval,
		&i.Concurrence,
		&i.ReminderRecurrence,
	)
	return i, err
}

const doseHistory = `-- name: DoseHistory :many
SELECT user_secret, delivery_method, dose, taken_at, taken_off_at, comment
FROM dosage_history
WHERE user_secret = $1
  AND taken_at >= $2
  AND taken_at < $3
  -- order latest last
ORDER BY taken_at ASC
`

type DoseHistoryParams struct {
	UserSecret userservice.Secret
	Start      pgtype.Timestamptz
	End        pgtype.Timestamptz
}

func (q *Queries) DoseHistory(ctx context.Context, arg DoseHistoryParams) ([]DosageHistory, error) {
	rows, err := q.db.Query(ctx, doseHistory, arg.UserSecret, arg.Start, arg.End)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DosageHistory
	for rows.Next() {
		var i DosageHistory
		if err := rows.Scan(
			&i.UserSecret,
			&i.DeliveryMethod,
			&i.Dose,
			&i.TakenAt,
			&i.TakenOffAt,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const editDose = `-- name: EditDose :execrows
UPDATE
  dosage_history
SET delivery_method = $1, dose = $2, taken_at = $3, taken_off_at = $4
WHERE user_secret = $5
  AND taken_at = $6
`

type EditDoseParams struct {
	DeliveryMethod pgtype.Text
	Dose           float32
	TakenAt        pgtype.Timestamptz
	TakenOffAt     pgtype.Timestamptz
	UserSecret     userservice.Secret
	OldTakenAt     pgtype.Timestamptz
}

func (q *Queries) EditDose(ctx context.Context, arg EditDoseParams) (int64, error) {
	result, err := q.db.Exec(ctx, editDose,
		arg.DeliveryMethod,
		arg.Dose,
		arg.TakenAt,
		arg.TakenOffAt,
		arg.UserSecret,
		arg.OldTakenAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const forgetDoses = `-- name: ForgetDoses :execrows
DELETE FROM dosage_history
WHERE user_secret = $1
  AND taken_at = ANY ($2::timestamptz[])
`

type ForgetDosesParams struct {
	UserSecret userservice.Secret
	TakenAt    []pgtype.Timestamptz
}

func (q *Queries) ForgetDoses(ctx context.Context, arg ForgetDosesParams) (int64, error) {
	result, err := q.db.Exec(ctx, forgetDoses, arg.UserSecret, arg.TakenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordDose = `-- name: RecordDose :exec
INSERT INTO dosage_history (user_secret, delivery_method, dose, taken_at, taken_off_at)
  VALUES ($1, $2, $3, $4, $5)
`

type RecordDoseParams struct {
	UserSecret     userservice.Secret
	DeliveryMethod pgtype.Text
	Dose           float32
	TakenAt        pgtype.Timestamptz
	TakenOffAt     pgtype.Timestamptz
}

func (q *Queries) RecordDose(ctx context.Context, arg RecordDoseParams) error {
	_, err := q.db.Exec(ctx, recordDose,
		arg.UserSecret,
		arg.DeliveryMethod,
		arg.Dose,
		arg.TakenAt,
		arg.TakenOffAt,
	)
	return err
}

const recordRemindedDoseAttempt = `-- name: RecordRemindedDoseAttempt :exec
INSERT INTO notification_history (user_secret, sent_at, supposed_entity_time, error_reason)
  VALUES ($1, $2, $3, $4)
`

type RecordRemindedDoseAttemptParams struct {
	UserSecret         userservice.Secret
	SentAt             pgtype.Timestamptz
	SupposedEntityTime pgtype.Timestamptz
	ErrorReason        pgtype.Text
}

func (q *Queries) RecordRemindedDoseAttempt(ctx context.Context, arg RecordRemindedDoseAttemptParams) error {
	_, err := q.db.Exec(ctx, recordRemindedDoseAttempt,
		arg.UserSecret,
		arg.SentAt,
		arg.SupposedEntityTime,
		arg.ErrorReason,
	)
	return err
}

const setDosageSchedule = `-- name: SetDosageSchedule :exec
INSERT INTO dosage_schedule (user_secret, delivery_method, dose, interval, concurrence, reminder_recurrence)
  VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_secret)
  DO UPDATE SET
    delivery_method = $2, dose = $3, interval = $4, concurrence = $5, reminder_recurrence = $6
`

type SetDosageScheduleParams struct {
	UserSecret         userservice.Secret
	DeliveryMethod     pgtype.Text
	Dose               float32
	Interval           pgtype.Interval
	Concurrence        pgtype.Int2
	ReminderRecurrence []pgtype.Interval
}

func (q *Queries) SetDosageSchedule(ctx context.Context, arg SetDosageScheduleParams) error {
	_, err := q.db.Exec(ctx, setDosageSchedule,
		arg.UserSecret,
		arg.DeliveryMethod,
		arg.Dose,
		arg.Interval,
		arg.Concurrence,
		arg.ReminderRecurrence,
	)
	return err
}

const upcomingDosageReminders = `-- name: UpcomingDosageReminders :many
SELECT DISTINCT ON (users.secret)
  users.secret AS user_secret, -- 
  users.name AS user_name, -- 
  dosage_schedule.user_secret, dosage_schedule.delivery_method, dosage_schedule.dose, dosage_schedule.interval, dosage_schedule.concurrence, dosage_schedule.reminder_recurrence, -- 
  dosage_history.user_secret, dosage_history.delivery_method, dosage_history.dose, dosage_history.taken_at, dosage_history.taken_off_at, dosage_history.comment, -- 
  notification_history.supposed_entity_time AS last_reminded_dose, -- 
  notification_history.sent_at AS last_reminded_at
FROM users
  INNER JOIN dosage_schedule ON users.secret = dosage_schedule.user_secret
  INNER JOIN dosage_history ON users.secret = dosage_history.user_secret
  LEFT JOIN notification_history ON users.secret = notification_history.user_secret
ORDER BY -- 
  users.secret, -- 
  dosage_history.taken_at DESC, -- 
  notification_history.supposed_entity_time DESC, -- 
  notification_history.sent_at DESC
`

type UpcomingDosageRemindersRow struct {
	UserSecret       userservice.Secret
	UserName         string
	DosageSchedule   DosageSchedule
	DosageHistory    DosageHistory
	LastRemindedDose pgtype.Timestamptz
	LastRemindedAt   pgtype.Timestamptz
}

func (q *Queries) UpcomingDosageReminders(ctx context.Context) ([]UpcomingDosageRemindersRow, error) {
	rows, err := q.db.Query(ctx, upcomingDosageReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpcomingDosageRemindersRow
	for rows.Next() {
		var i UpcomingDosageRemindersRow
		if err := rows.Scan(
			&i.UserSecret,
			&i.UserName,
			&i.DosageSchedule.UserSecret,
			&i.DosageSchedule.DeliveryMethod,
			&i.DosageSchedule.Dose,
			&i.DosageSchedule.Interval,
			&i.DosageSchedule.Concurrence,
			&i.DosageSchedule.ReminderRecurrence,
			&i.DosageHistory.UserSecret,
			&i.DosageHistory.DeliveryMethod,
			&i.DosageHistory.Dose,
			&i.DosageHistory.TakenAt,
			&i.DosageHistory.TakenOffAt,
			&i.DosageHistory.Comment,
			&i.LastRemindedDose,
			&i.LastRemindedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
