// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: meta.sql

package postgresqlc

import (
	"context"
)

const version = `-- name: Version :one
/*
 * Meta
 */
SELECT v
FROM meta
`

func (q *Queries) Version(ctx context.Context) (int16, error) {
	row := q.db.QueryRow(ctx, version)
	var v int16
	err := row.Scan(&v)
	return v, err
}
