// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgresqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	notificationservice "libdb.so/e2clicker/services/notification"
	userservice "libdb.so/e2clicker/services/user"
)

type DeliveryMethod struct {
	ID    string
	Units string
	Name  string
}

type DosageHistory struct {
	DoseID         int64
	UserSecret     userservice.Secret
	DeliveryMethod pgtype.Text
	Dose           float32
	TakenAt        pgtype.Timestamptz
	TakenOffAt     pgtype.Timestamptz
}

type DosageSchedule struct {
	UserSecret     userservice.Secret
	DeliveryMethod pgtype.Text
	Dose           float32
	Interval       pgtype.Interval
	Concurrence    pgtype.Int2
}

type Meta struct {
	X bool
	V int16
}

type NotificationHistory struct {
	NotificationID int64
	UserSecret     userservice.Secret
	DosageID       pgtype.Int8
	SentAt         pgtype.Timestamptz
	ErrorReason    pgtype.Text
}

type User struct {
	Secret                  userservice.Secret
	Name                    string
	Locale                  userservice.Locale
	RegisteredAt            pgtype.Timestamp
	NotificationPreferences *notificationservice.UserPreferences
}

type UserAvatar struct {
	UserSecret  userservice.Secret
	MIMEType    string
	AvatarImage []byte
}

type UserSession struct {
	ID         int64
	UserSecret userservice.Secret
	Token      []byte
	CreatedAt  pgtype.Timestamp
	LastUsed   pgtype.Timestamp
	UserAgent  pgtype.Text
}

type UsersWithAvatar struct {
	Secret    userservice.Secret
	Name      string
	Locale    userservice.Locale
	HasAvatar bool
}
