// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgresqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	sqlc "libdb.so/e2clicker/internal/sqlc"
	notificationservice "libdb.so/e2clicker/services/notification"
	userservice "libdb.so/e2clicker/services/user"
)

type DeliveryMethod struct {
	ID    string
	Units string
	Name  string
}

type DosageHistory struct {
	DoseID         int64
	LastDose       pgtype.Int8
	UserID         interface{}
	DeliveryMethod pgtype.Text
	Dose           pgtype.Numeric
	TakenAt        pgtype.Timestamptz
	TakenOffAt     pgtype.Timestamptz
}

type DosageSchedule struct {
	UserID         sqlc.UserID
	DeliveryMethod pgtype.Text
	Dose           pgtype.Numeric
	Interval       pgtype.Interval
	Concurrence    pgtype.Numeric
}

type Meta struct {
	X bool
	V int16
}

type NotificationHistory struct {
	NotificationID int64
	UserID         interface{}
	DosageID       pgtype.Int8
	SentAt         pgtype.Timestamptz
	ErrorReason    pgtype.Text
}

type User struct {
	UserID              sqlc.UserID
	Email               string
	Passhash            []byte
	Name                string
	Locale              userservice.Locale
	RegisteredAt        pgtype.Timestamp
	NotificationService *notificationservice.NotificationConfigJSON
	CustomNotification  *notificationservice.Notification
}

type UserAvatar struct {
	UserID      sqlc.UserID
	MIMEType    string
	AvatarImage []byte
}

type UserSession struct {
	SessionID int64
	UserID    sqlc.UserID
	Token     []byte
	CreatedAt pgtype.Timestamp
	LastUsed  pgtype.Timestamp
	UserAgent pgtype.Text
}
