schema = 3

[mod]
  [mod.'github.com/SherClockHolmes/webpush-go']
    version = 'v1.4.0'
    hash = 'sha256-FduHfJgMV9U79idr7c3S64t0mCO5YnZS5o6G1qkV7Dc='

  [mod.'github.com/alecthomas/assert/v2']
    version = 'v2.11.0'
    hash = 'sha256-tDJCDKZ0R4qNA7hgMKWrpDyogt1802LCJDBCExxdqaU='

  [mod.'github.com/alecthomas/repr']
    version = 'v0.5.2'
    hash = 'sha256-PfIeyHh7xTbDN0g2otuDyUOQqbgS4KftVC1JKZ+6sdM='

  [mod.'github.com/apapsch/go-jsonmerge/v2']
    version = 'v2.0.0'
    hash = 'sha256-xp/1B6XUN2EbddBfoUkTV3oTk+34m4kOZP+66HhfLg4='

  [mod.'github.com/davecgh/go-spew']
    version = 'v1.1.2-0.20180830191138-d8f796af33cc'
    hash = 'sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc='

  [mod.'github.com/getkin/kin-openapi']
    version = 'v0.137.0'
    hash = 'sha256-9EG4IoEHGBWsZslgNMxupyZOBPMASklE/IbFUWXQGgs='

  [mod.'github.com/go-chi/chi/v5']
    version = 'v5.2.5'
    hash = 'sha256-Y1+17ky94849aqk3iKf30F1u+G6K3nzZzLOBSeqIUow='

  [mod.'github.com/go-openapi/jsonpointer']
    version = 'v0.23.1'
    hash = 'sha256-1vusGH4zPsJU1nPOJK73gh/qF8bvgM7K9ufMoV/Oa50='

  [mod.'github.com/go-openapi/swag/jsonname']
    version = 'v0.26.0'
    hash = 'sha256-vhWO27K+YiKrK/PStjAhqwrVXTF/d4xqxF3TzMtHg3Q='

  [mod.'github.com/golang-jwt/jwt/v5']
    version = 'v5.3.1'
    hash = 'sha256-h7AszH+3YWL3IV0+miY9vbtU0gM/2RpuASSGAYAgWcA='

  [mod.'github.com/google/uuid']
    version = 'v1.6.0'
    hash = 'sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw='

  [mod.'github.com/gorilla/mux']
    version = 'v1.8.1'
    hash = 'sha256-nDABvAhlYgxUW2N/brrep7NkQXoSGcHhA+XI4+tK0F0='

  [mod.'github.com/hexops/gotextdiff']
    version = 'v1.0.3'
    hash = 'sha256-wVs5uJs2KHU1HnDCDdSe0vIgNZylvs8oNidDxwA3+O0='

  [mod.'github.com/jackc/pgpassfile']
    version = 'v1.0.0'
    hash = 'sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM='

  [mod.'github.com/jackc/pgservicefile']
    version = 'v0.0.0-20240606120523-5a60cdf6a761'
    hash = 'sha256-ETpGsLAA2wcm5xJBayr/mZrCE1YsWbnkbSSX3ptrFn0='

  [mod.'github.com/jackc/pgx/v5']
    version = 'v5.9.2'
    hash = 'sha256-+R23f/i6n/iUkwc33WadubkUNIslDQraeLWdFdOXGD8='

  [mod.'github.com/jackc/puddle/v2']
    version = 'v2.2.2'
    hash = 'sha256-IUxdu4JYfsCh/qlz2SiUWu7EVPHhyooiVA4oaS2Z6yk='

  [mod.'github.com/josharian/intern']
    version = 'v1.0.0'
    hash = 'sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0='

  [mod.'github.com/lmittmann/tint']
    version = 'v0.0.0-20241125184319-3f947943fed6'
    hash = 'sha256-3BNwbiJ6PIGCiOAmhLfUUfGl5S/hx3sUpBkXQae5Jy0='
    replaced = 'github.com/diamondburned/tint'

  [mod.'github.com/mailru/easyjson']
    version = 'v0.9.2'
    hash = 'sha256-178Wz0XN1ghBYXWYQMSbByqPfsUc0mAf+p6j6mAJ4jg='

  [mod.'github.com/mohae/deepcopy']
    version = 'v0.0.0-20170929034955-c48cc78d4826'
    hash = 'sha256-TQMmKqIYwVhmMVh4RYQkAui97Eyj7poLmcAuDcHXsEk='

  [mod.'github.com/neilotoole/slogt']
    version = 'v1.1.0'
    hash = 'sha256-afBaGoRz0liungu8ZiedVJ1x9C/MV4spTw0It4Kh4ZI='

  [mod.'github.com/oapi-codegen/runtime']
    version = 'v1.4.0'
    hash = 'sha256-02RFkg6tlP6DI0IlYIEjwkUbE11cXLw17H/Ey4zxA0k='

  [mod.'github.com/oasdiff/yaml']
    version = 'v0.0.9'
    hash = 'sha256-je1aZ/MUidJRSTfJs8NpbWC63z73MUnU+SD3baiaDgY='

  [mod.'github.com/oasdiff/yaml3']
    version = 'v0.0.12'
    hash = 'sha256-/Dcdd+K90WIWqjaomw7MsmlzWATQCxTMlKQkjYRTYc0='

  [mod.'github.com/perimeterx/marshmallow']
    version = 'v1.1.5'
    hash = 'sha256-fFWjg0FNohDSV0/wUjQ8fBq1g8h6yIqTrHkxqL2Tt0s='

  [mod.'github.com/pmezard/go-difflib']
    version = 'v1.0.1-0.20181226105442-5d4384ee4fb2'
    hash = 'sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90='

  [mod.'github.com/puzpuzpuz/xsync/v3']
    version = 'v3.5.1'
    hash = 'sha256-yAf9Ye4XmtnhK3cxaUCjdGZWH+0WRNIczwCW3CPKUUw='

  [mod.'github.com/santhosh-tekuri/jsonschema/v6']
    version = 'v6.0.2'
    hash = 'sha256-rPRYeV00NRyt6rb+gFJRK1K4TlVxy92cocRK/X9Wef4='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.10'
    hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='

  [mod.'github.com/timewasted/go-accept-headers']
    version = 'v0.0.0-20130320203746-c78f304b1b09'
    hash = 'sha256-msv1C6gIrxfFhP0nLzDCtDT5F9I597zqesk0li3rqec='

  [mod.'github.com/woodsbury/decimal128']
    version = 'v1.4.0'
    hash = 'sha256-iywk2bDtlSY2Lg3n71356eEYezc7wCtLozSGAEz+6FE='

  [mod.'go.uber.org/dig']
    version = 'v1.19.0'
    hash = 'sha256-/27soFu058DqVt8F4Yoq987lwqS+iz5n2bMGawclrfI='

  [mod.'go.uber.org/fx']
    version = 'v1.24.0'
    hash = 'sha256-AZxnrgAYFuud9V9tXjvoEeWlqMdZD0Af+Bn6hcz6XvQ='

  [mod.'go.uber.org/multierr']
    version = 'v1.11.0'
    hash = 'sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0='

  [mod.'go.uber.org/zap']
    version = 'v1.28.0'
    hash = 'sha256-x+MIioLe/gBKjZyRc8shaBR5nO5Pv++8U9gHPZ5W+5A='

  [mod.'golang.org/x/crypto']
    version = 'v0.50.0'
    hash = 'sha256-vC1BJT7+3UBWLyEE5n3to0NKhMo6m2HGow2HiFgpQLo='

  [mod.'golang.org/x/sync']
    version = 'v0.20.0'
    hash = 'sha256-ybcjhCfK6lroUM0yswUvWooW8MOQZBXyiSqoxG6Uy0Y='

  [mod.'golang.org/x/sys']
    version = 'v0.43.0'
    hash = 'sha256-aDQXqSTZES2l/132PBxhZN4ywldpPyfm7LByYCHzzwM='

  [mod.'golang.org/x/text']
    version = 'v0.36.0'
    hash = 'sha256-/0t9C6Mc8kYjxweFB0us2lGKo8GovHhBiq5nlMOppC0='

  [mod.'golang.org/x/time']
    version = 'v0.15.0'
    hash = 'sha256-5D24A65wn7k93Jj3+918UKjB9ccmGHPBEqjD2XDB92E='

  [mod.'gopkg.in/alexcesaro/quotedprintable.v3']
    version = 'v3.0.0-20150716171945-2caba252f4dc'
    hash = 'sha256-6cgI1fteSkqNYkNeReaHz0El7hbomNiRyueg44BHI7o='

  [mod.'gopkg.in/mail.v2']
    version = 'v2.3.1'
    hash = 'sha256-cXPPOheoKJ6IV01X6ptNazZRw91UrIA1MKuIYrbM8xA='

  [mod.'libdb.so/ctxt']
    version = 'v0.0.0-20240229093153-2db38a5d3c12'
    hash = 'sha256-mViBj67wYeuD4mQKMP/4gQo9lFNO6J8HZztHw9ZGPlk='

  [mod.'libdb.so/hserve']
    version = 'v0.0.0-20230404043009-95e112a6e0a5'
    hash = 'sha256-rXOzmWt4UqadlrVaazD7XVXYCEG5hV5ZuyJ+KcoW3as='

  [mod.'libdb.so/lazymigrate']
    version = 'v0.0.0-20240811151247-0597fc52ac48'
    hash = 'sha256-tfSzwQvmVfL/uDtCeM1s8yVhNMrpbO7NmNIyuMfffwg='

  [mod.'libdb.so/xcsv']
    version = 'v0.0.0-20241122012224-49de41730f5a'
    hash = 'sha256-JFFRXCMUp5bak7vFyrOxxxbxNKYNX7j2FVQAAOFe+co='
