schema = 4
vendorModulesTxt = "# github.com/alecthomas/assert/v2 v2.10.0\n## explicit; go 1.18\ngithub.com/alecthomas/assert/v2\n# github.com/alecthomas/repr v0.4.0\n## explicit; go 1.18\ngithub.com/alecthomas/repr\n# github.com/apapsch/go-jsonmerge/v2 v2.0.0\n## explicit; go 1.12\ngithub.com/apapsch/go-jsonmerge/v2\n# github.com/elithrar/simple-scrypt v1.3.0\n## explicit\ngithub.com/elithrar/simple-scrypt\n# github.com/go-chi/chi/v5 v5.1.0\n## explicit; go 1.14\ngithub.com/go-chi/chi/v5\n# github.com/google/uuid v1.5.0\n## explicit\ngithub.com/google/uuid\n# github.com/hexops/gotextdiff v1.0.3\n## explicit; go 1.16\ngithub.com/hexops/gotextdiff\ngithub.com/hexops/gotextdiff/myers\ngithub.com/hexops/gotextdiff/span\n# github.com/jackc/pgpassfile v1.0.0\n## explicit; go 1.12\ngithub.com/jackc/pgpassfile\n# github.com/jackc/pgservicefile v0.0.0-20221227161230-091c0ba34f0a\n## explicit; go 1.14\ngithub.com/jackc/pgservicefile\n# github.com/jackc/pgx/v5 v5.6.0\n## explicit; go 1.20\ngithub.com/jackc/pgx/v5\ngithub.com/jackc/pgx/v5/internal/iobufpool\ngithub.com/jackc/pgx/v5/internal/pgio\ngithub.com/jackc/pgx/v5/internal/sanitize\ngithub.com/jackc/pgx/v5/internal/stmtcache\ngithub.com/jackc/pgx/v5/pgconn\ngithub.com/jackc/pgx/v5/pgconn/ctxwatch\ngithub.com/jackc/pgx/v5/pgconn/internal/bgreader\ngithub.com/jackc/pgx/v5/pgproto3\ngithub.com/jackc/pgx/v5/pgtype\ngithub.com/jackc/pgx/v5/pgxpool\n# github.com/jackc/puddle/v2 v2.2.1\n## explicit; go 1.19\ngithub.com/jackc/puddle/v2\ngithub.com/jackc/puddle/v2/internal/genstack\n# github.com/lmittmann/tint v1.0.5\n## explicit; go 1.21\ngithub.com/lmittmann/tint\n# github.com/oapi-codegen/runtime v1.1.1\n## explicit; go 1.20\ngithub.com/oapi-codegen/runtime\ngithub.com/oapi-codegen/runtime/strictmiddleware/nethttp\ngithub.com/oapi-codegen/runtime/types\n# github.com/rs/xid v1.5.0\n## explicit; go 1.12\ngithub.com/rs/xid\n# github.com/samber/do/v2 v2.0.0-beta.7\n## explicit; go 1.18\ngithub.com/samber/do/v2\ngithub.com/samber/do/v2/stacktrace\n# github.com/samber/go-type-to-string v1.4.0\n## explicit; go 1.18\ngithub.com/samber/go-type-to-string\n# github.com/spf13/pflag v1.0.5\n## explicit; go 1.12\ngithub.com/spf13/pflag\n# golang.org/x/crypto v0.17.0\n## explicit; go 1.18\ngolang.org/x/crypto/pbkdf2\ngolang.org/x/crypto/scrypt\n# golang.org/x/sync v0.1.0\n## explicit\ngolang.org/x/sync/semaphore\n# golang.org/x/text v0.14.0\n## explicit; go 1.18\ngolang.org/x/text/cases\ngolang.org/x/text/internal\ngolang.org/x/text/internal/language\ngolang.org/x/text/internal/language/compact\ngolang.org/x/text/internal/tag\ngolang.org/x/text/language\ngolang.org/x/text/runes\ngolang.org/x/text/secure/bidirule\ngolang.org/x/text/secure/precis\ngolang.org/x/text/transform\ngolang.org/x/text/unicode/bidi\ngolang.org/x/text/unicode/norm\ngolang.org/x/text/width\n# libdb.so/hserve v0.0.0-20230404043009-95e112a6e0a5\n## explicit; go 1.15\nlibdb.so/hserve\n# libdb.so/lazymigrate v0.0.0-20240811151247-0597fc52ac48\n## explicit; go 1.21.0\nlibdb.so/lazymigrate\n"

[mod]
  [mod."github.com/alecthomas/assert/v2"]
    version = "v2.10.0"
    hash = "sha256-qlGX967uGoMveXL/iYFbmx0NNJfRMEGkW2HN+Pr7RCM="
  [mod."github.com/alecthomas/repr"]
    version = "v0.4.0"
    hash = "sha256-CyAzMSTfLGHDtfGXi91y7XMVpPUDNOKjsznb+osl9dU="
  [mod."github.com/apapsch/go-jsonmerge/v2"]
    version = "v2.0.0"
    hash = "sha256-xp/1B6XUN2EbddBfoUkTV3oTk+34m4kOZP+66HhfLg4="
  [mod."github.com/elithrar/simple-scrypt"]
    version = "v1.3.0"
    hash = "sha256-7n+dG2kWBu8fYSRxx6oEbmnW1UmtMiDokZ0l357hfvY="
  [mod."github.com/go-chi/chi/v5"]
    version = "v5.1.0"
    hash = "sha256-DpVfbPlJe4zQNdBrirWq9Q37/awSu5zb3IJgcuyEED8="
  [mod."github.com/google/uuid"]
    version = "v1.5.0"
    hash = "sha256-DasOte4xANR1VND5XEHKGhpGiyYq74TJmNrgWeIRX4U="
  [mod."github.com/hexops/gotextdiff"]
    version = "v1.0.3"
    hash = "sha256-wVs5uJs2KHU1HnDCDdSe0vIgNZylvs8oNidDxwA3+O0="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20221227161230-091c0ba34f0a"
    hash = "sha256-rBtUw15WPPDp2eulHXH5e2zCIed1OPFYwlCpgDOnGRM="
  [mod."github.com/jackc/pgx/v5"]
    version = "v5.6.0"
    hash = "sha256-6Tx7UF6gWc4e572x6wBDLghoe0Inhef0cH2Fq5I8fX4="
  [mod."github.com/jackc/puddle/v2"]
    version = "v2.2.1"
    hash = "sha256-Edf8SLT/8l+xfHm9IjUGxs1MHtic2VgRyfqb6OzGA9k="
  [mod."github.com/lmittmann/tint"]
    version = "v1.0.5"
    hash = "sha256-NthPT7c1Q2VSp5IrWMGAvzX7AxEcTKk+O0F56pgaTsQ="
  [mod."github.com/oapi-codegen/runtime"]
    version = "v1.1.1"
    hash = "sha256-GRvzpQngQPAy59KvvcwhjYqjx4gttIhOtQKjqfQcNvI="
  [mod."github.com/rs/xid"]
    version = "v1.5.0"
    hash = "sha256-u0QLm2YFMJqEjUhpWcLwfoS9lNHUxc2A79MObsqVbVU="
  [mod."github.com/samber/do/v2"]
    version = "v2.0.0-beta.7"
    hash = "sha256-9LscTeCAfZmIIVDdaqnwr7T9NpvMmpV//lpaGzI63hQ="
  [mod."github.com/samber/go-type-to-string"]
    version = "v1.4.0"
    hash = "sha256-a52PHa8fhEa8zXy8kLklurzp6ZaZynkuAGCd3h0IdB0="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."golang.org/x/crypto"]
    version = "v0.17.0"
    hash = "sha256-/vzBaeD/Ymyc7cpjBvSfJfuZ57zWa9LOaZM7b33eIx0="
  [mod."golang.org/x/sync"]
    version = "v0.1.0"
    hash = "sha256-Hygjq9euZ0qz6TvHYQwOZEjNiTbTh1nSLRAWZ6KFGR8="
  [mod."golang.org/x/text"]
    version = "v0.14.0"
    hash = "sha256-yh3B0tom1RfzQBf1RNmfdNWF1PtiqxV41jW1GVS6JAg="
  [mod."libdb.so/hserve"]
    version = "v0.0.0-20230404043009-95e112a6e0a5"
    hash = "sha256-rXOzmWt4UqadlrVaazD7XVXYCEG5hV5ZuyJ+KcoW3as="
  [mod."libdb.so/lazymigrate"]
    version = "v0.0.0-20240811151247-0597fc52ac48"
    hash = "sha256-tfSzwQvmVfL/uDtCeM1s8yVhNMrpbO7NmNIyuMfffwg="
