// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package dosage

import (
	"context"
	"e2clicker.app/services/notification"
	"e2clicker.app/services/notification/openapi"
	"e2clicker.app/services/user"
	"sync"
)

// Ensure, that UserNotificationServiceMock does implement notification.UserNotificationService.
// If this is not the case, regenerate this file with moq.
var _ notification.UserNotificationService = &UserNotificationServiceMock{}

// UserNotificationServiceMock is a mock implementation of notification.UserNotificationService.
//
//	func TestSomethingThatUsesUserNotificationService(t *testing.T) {
//
//		// make and configure a mocked notification.UserNotificationService
//		mockedUserNotificationService := &UserNotificationServiceMock{
//			NotifyUserFunc: func(ctx context.Context, secret user.Secret, t openapi.NotificationType) error {
//				panic("mock out the NotifyUser method")
//			},
//			SetUserPreferencesFunc: func(ctx context.Context, secret user.Secret, preferences *notification.UserPreferences) error {
//				panic("mock out the SetUserPreferences method")
//			},
//			SetUserPreferencesSafeFunc: func(ctx context.Context, secret user.Secret, newPreferences *notification.UserPreferences, oldPreferences *notification.UserPreferences) error {
//				panic("mock out the SetUserPreferencesSafe method")
//			},
//			UserPreferencesFunc: func(ctx context.Context, secret user.Secret) (notification.UserPreferences, error) {
//				panic("mock out the UserPreferences method")
//			},
//		}
//
//		// use mockedUserNotificationService in code that requires notification.UserNotificationService
//		// and then make assertions.
//
//	}
type UserNotificationServiceMock struct {
	// NotifyUserFunc mocks the NotifyUser method.
	NotifyUserFunc func(ctx context.Context, secret user.Secret, t openapi.NotificationType) error

	// SetUserPreferencesFunc mocks the SetUserPreferences method.
	SetUserPreferencesFunc func(ctx context.Context, secret user.Secret, preferences *notification.UserPreferences) error

	// SetUserPreferencesSafeFunc mocks the SetUserPreferencesSafe method.
	SetUserPreferencesSafeFunc func(ctx context.Context, secret user.Secret, newPreferences *notification.UserPreferences, oldPreferences *notification.UserPreferences) error

	// UserPreferencesFunc mocks the UserPreferences method.
	UserPreferencesFunc func(ctx context.Context, secret user.Secret) (notification.UserPreferences, error)

	// calls tracks calls to the methods.
	calls struct {
		// NotifyUser holds details about calls to the NotifyUser method.
		NotifyUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Secret is the secret argument value.
			Secret user.Secret
			// T is the t argument value.
			T openapi.NotificationType
		}
		// SetUserPreferences holds details about calls to the SetUserPreferences method.
		SetUserPreferences []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Secret is the secret argument value.
			Secret user.Secret
			// Preferences is the preferences argument value.
			Preferences *notification.UserPreferences
		}
		// SetUserPreferencesSafe holds details about calls to the SetUserPreferencesSafe method.
		SetUserPreferencesSafe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Secret is the secret argument value.
			Secret user.Secret
			// NewPreferences is the newPreferences argument value.
			NewPreferences *notification.UserPreferences
			// OldPreferences is the oldPreferences argument value.
			OldPreferences *notification.UserPreferences
		}
		// UserPreferences holds details about calls to the UserPreferences method.
		UserPreferences []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Secret is the secret argument value.
			Secret user.Secret
		}
	}
	lockNotifyUser             sync.RWMutex
	lockSetUserPreferences     sync.RWMutex
	lockSetUserPreferencesSafe sync.RWMutex
	lockUserPreferences        sync.RWMutex
}

// NotifyUser calls NotifyUserFunc.
func (mock *UserNotificationServiceMock) NotifyUser(ctx context.Context, secret user.Secret, t openapi.NotificationType) error {
	if mock.NotifyUserFunc == nil {
		panic("UserNotificationServiceMock.NotifyUserFunc: method is nil but UserNotificationService.NotifyUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Secret user.Secret
		T      openapi.NotificationType
	}{
		Ctx:    ctx,
		Secret: secret,
		T:      t,
	}
	mock.lockNotifyUser.Lock()
	mock.calls.NotifyUser = append(mock.calls.NotifyUser, callInfo)
	mock.lockNotifyUser.Unlock()
	return mock.NotifyUserFunc(ctx, secret, t)
}

// NotifyUserCalls gets all the calls that were made to NotifyUser.
// Check the length with:
//
//	len(mockedUserNotificationService.NotifyUserCalls())
func (mock *UserNotificationServiceMock) NotifyUserCalls() []struct {
	Ctx    context.Context
	Secret user.Secret
	T      openapi.NotificationType
} {
	var calls []struct {
		Ctx    context.Context
		Secret user.Secret
		T      openapi.NotificationType
	}
	mock.lockNotifyUser.RLock()
	calls = mock.calls.NotifyUser
	mock.lockNotifyUser.RUnlock()
	return calls
}

// SetUserPreferences calls SetUserPreferencesFunc.
func (mock *UserNotificationServiceMock) SetUserPreferences(ctx context.Context, secret user.Secret, preferences *notification.UserPreferences) error {
	if mock.SetUserPreferencesFunc == nil {
		panic("UserNotificationServiceMock.SetUserPreferencesFunc: method is nil but UserNotificationService.SetUserPreferences was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Secret      user.Secret
		Preferences *notification.UserPreferences
	}{
		Ctx:         ctx,
		Secret:      secret,
		Preferences: preferences,
	}
	mock.lockSetUserPreferences.Lock()
	mock.calls.SetUserPreferences = append(mock.calls.SetUserPreferences, callInfo)
	mock.lockSetUserPreferences.Unlock()
	return mock.SetUserPreferencesFunc(ctx, secret, preferences)
}

// SetUserPreferencesCalls gets all the calls that were made to SetUserPreferences.
// Check the length with:
//
//	len(mockedUserNotificationService.SetUserPreferencesCalls())
func (mock *UserNotificationServiceMock) SetUserPreferencesCalls() []struct {
	Ctx         context.Context
	Secret      user.Secret
	Preferences *notification.UserPreferences
} {
	var calls []struct {
		Ctx         context.Context
		Secret      user.Secret
		Preferences *notification.UserPreferences
	}
	mock.lockSetUserPreferences.RLock()
	calls = mock.calls.SetUserPreferences
	mock.lockSetUserPreferences.RUnlock()
	return calls
}

// SetUserPreferencesSafe calls SetUserPreferencesSafeFunc.
func (mock *UserNotificationServiceMock) SetUserPreferencesSafe(ctx context.Context, secret user.Secret, newPreferences *notification.UserPreferences, oldPreferences *notification.UserPreferences) error {
	if mock.SetUserPreferencesSafeFunc == nil {
		panic("UserNotificationServiceMock.SetUserPreferencesSafeFunc: method is nil but UserNotificationService.SetUserPreferencesSafe was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Secret         user.Secret
		NewPreferences *notification.UserPreferences
		OldPreferences *notification.UserPreferences
	}{
		Ctx:            ctx,
		Secret:         secret,
		NewPreferences: newPreferences,
		OldPreferences: oldPreferences,
	}
	mock.lockSetUserPreferencesSafe.Lock()
	mock.calls.SetUserPreferencesSafe = append(mock.calls.SetUserPreferencesSafe, callInfo)
	mock.lockSetUserPreferencesSafe.Unlock()
	return mock.SetUserPreferencesSafeFunc(ctx, secret, newPreferences, oldPreferences)
}

// SetUserPreferencesSafeCalls gets all the calls that were made to SetUserPreferencesSafe.
// Check the length with:
//
//	len(mockedUserNotificationService.SetUserPreferencesSafeCalls())
func (mock *UserNotificationServiceMock) SetUserPreferencesSafeCalls() []struct {
	Ctx            context.Context
	Secret         user.Secret
	NewPreferences *notification.UserPreferences
	OldPreferences *notification.UserPreferences
} {
	var calls []struct {
		Ctx            context.Context
		Secret         user.Secret
		NewPreferences *notification.UserPreferences
		OldPreferences *notification.UserPreferences
	}
	mock.lockSetUserPreferencesSafe.RLock()
	calls = mock.calls.SetUserPreferencesSafe
	mock.lockSetUserPreferencesSafe.RUnlock()
	return calls
}

// UserPreferences calls UserPreferencesFunc.
func (mock *UserNotificationServiceMock) UserPreferences(ctx context.Context, secret user.Secret) (notification.UserPreferences, error) {
	if mock.UserPreferencesFunc == nil {
		panic("UserNotificationServiceMock.UserPreferencesFunc: method is nil but UserNotificationService.UserPreferences was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Secret user.Secret
	}{
		Ctx:    ctx,
		Secret: secret,
	}
	mock.lockUserPreferences.Lock()
	mock.calls.UserPreferences = append(mock.calls.UserPreferences, callInfo)
	mock.lockUserPreferences.Unlock()
	return mock.UserPreferencesFunc(ctx, secret)
}

// UserPreferencesCalls gets all the calls that were made to UserPreferences.
// Check the length with:
//
//	len(mockedUserNotificationService.UserPreferencesCalls())
func (mock *UserNotificationServiceMock) UserPreferencesCalls() []struct {
	Ctx    context.Context
	Secret user.Secret
} {
	var calls []struct {
		Ctx    context.Context
		Secret user.Secret
	}
	mock.lockUserPreferences.RLock()
	calls = mock.calls.UserPreferences
	mock.lockUserPreferences.RUnlock()
	return calls
}
