// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package dosage

import (
	"context"
	"sync"
)

// Ensure, that DosageReminderStorageMock does implement DosageReminderStorage.
// If this is not the case, regenerate this file with moq.
var _ DosageReminderStorage = &DosageReminderStorageMock{}

// DosageReminderStorageMock is a mock implementation of DosageReminderStorage.
//
//	func TestSomethingThatUsesDosageReminderStorage(t *testing.T) {
//
//		// make and configure a mocked DosageReminderStorage
//		mockedDosageReminderStorage := &DosageReminderStorageMock{
//			RecordRemindedDoseAttemptsFunc: func(ctx context.Context, remindedDoses []RemindedDoseAttempt) error {
//				panic("mock out the RecordRemindedDoseAttempts method")
//			},
//			UpcomingDosageRemindersFunc: func(ctx context.Context) ([]DosageReminder, error) {
//				panic("mock out the UpcomingDosageReminders method")
//			},
//		}
//
//		// use mockedDosageReminderStorage in code that requires DosageReminderStorage
//		// and then make assertions.
//
//	}
type DosageReminderStorageMock struct {
	// RecordRemindedDoseAttemptsFunc mocks the RecordRemindedDoseAttempts method.
	RecordRemindedDoseAttemptsFunc func(ctx context.Context, remindedDoses []RemindedDoseAttempt) error

	// UpcomingDosageRemindersFunc mocks the UpcomingDosageReminders method.
	UpcomingDosageRemindersFunc func(ctx context.Context) ([]DosageReminder, error)

	// calls tracks calls to the methods.
	calls struct {
		// RecordRemindedDoseAttempts holds details about calls to the RecordRemindedDoseAttempts method.
		RecordRemindedDoseAttempts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RemindedDoses is the remindedDoses argument value.
			RemindedDoses []RemindedDoseAttempt
		}
		// UpcomingDosageReminders holds details about calls to the UpcomingDosageReminders method.
		UpcomingDosageReminders []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockRecordRemindedDoseAttempts sync.RWMutex
	lockUpcomingDosageReminders    sync.RWMutex
}

// RecordRemindedDoseAttempts calls RecordRemindedDoseAttemptsFunc.
func (mock *DosageReminderStorageMock) RecordRemindedDoseAttempts(ctx context.Context, remindedDoses []RemindedDoseAttempt) error {
	if mock.RecordRemindedDoseAttemptsFunc == nil {
		panic("DosageReminderStorageMock.RecordRemindedDoseAttemptsFunc: method is nil but DosageReminderStorage.RecordRemindedDoseAttempts was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		RemindedDoses []RemindedDoseAttempt
	}{
		Ctx:           ctx,
		RemindedDoses: remindedDoses,
	}
	mock.lockRecordRemindedDoseAttempts.Lock()
	mock.calls.RecordRemindedDoseAttempts = append(mock.calls.RecordRemindedDoseAttempts, callInfo)
	mock.lockRecordRemindedDoseAttempts.Unlock()
	return mock.RecordRemindedDoseAttemptsFunc(ctx, remindedDoses)
}

// RecordRemindedDoseAttemptsCalls gets all the calls that were made to RecordRemindedDoseAttempts.
// Check the length with:
//
//	len(mockedDosageReminderStorage.RecordRemindedDoseAttemptsCalls())
func (mock *DosageReminderStorageMock) RecordRemindedDoseAttemptsCalls() []struct {
	Ctx           context.Context
	RemindedDoses []RemindedDoseAttempt
} {
	var calls []struct {
		Ctx           context.Context
		RemindedDoses []RemindedDoseAttempt
	}
	mock.lockRecordRemindedDoseAttempts.RLock()
	calls = mock.calls.RecordRemindedDoseAttempts
	mock.lockRecordRemindedDoseAttempts.RUnlock()
	return calls
}

// UpcomingDosageReminders calls UpcomingDosageRemindersFunc.
func (mock *DosageReminderStorageMock) UpcomingDosageReminders(ctx context.Context) ([]DosageReminder, error) {
	if mock.UpcomingDosageRemindersFunc == nil {
		panic("DosageReminderStorageMock.UpcomingDosageRemindersFunc: method is nil but DosageReminderStorage.UpcomingDosageReminders was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockUpcomingDosageReminders.Lock()
	mock.calls.UpcomingDosageReminders = append(mock.calls.UpcomingDosageReminders, callInfo)
	mock.lockUpcomingDosageReminders.Unlock()
	return mock.UpcomingDosageRemindersFunc(ctx)
}

// UpcomingDosageRemindersCalls gets all the calls that were made to UpcomingDosageReminders.
// Check the length with:
//
//	len(mockedDosageReminderStorage.UpcomingDosageRemindersCalls())
func (mock *DosageReminderStorageMock) UpcomingDosageRemindersCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockUpcomingDosageReminders.RLock()
	calls = mock.calls.UpcomingDosageReminders
	mock.lockUpcomingDosageReminders.RUnlock()
	return calls
}
