// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version (devel) DO NOT EDIT.
package openapi

import (
	"time"
)

// Defines values for ExportDosageHistoryParamsAccept.
const (
	ExportDosageHistoryParamsAcceptApplicationJSON ExportDosageHistoryParamsAccept = "application/json"
	ExportDosageHistoryParamsAcceptTextCsv         ExportDosageHistoryParamsAccept = "text/csv"
)

// Defines values for ImportDosageHistoryParamsContentType.
const (
	ImportDosageHistoryParamsContentTypeApplicationJSON ImportDosageHistoryParamsContentType = "application/json"
	ImportDosageHistoryParamsContentTypeTextCsv         ImportDosageHistoryParamsContentType = "text/csv"
)

// DeliveryMethod defines model for DeliveryMethod.
type DeliveryMethod struct {
	// ID A short string representing the delivery method. This is what goes into the DeliveryMethod fields.
	ID string `json:"id"`

	// Units The units of the delivery method.
	Units string `json:"units"`

	// Name The full name of the delivery method.
	Name string `json:"name"`

	// Description A description of the delivery method.
	Description string `json:"description,omitempty"`
}

// Dosage defines model for Dosage.
type Dosage struct {
	// DeliveryMethod The delivery method to use.
	DeliveryMethod string `json:"deliveryMethod"`

	// Dose The dosage amount.
	Dose float32 `json:"dose"`

	// Interval The interval between doses in days.
	Interval float64 `json:"interval"`

	// Concurrence The number of estrogen patches on the body at once. Only relevant if delivery method is patch.
	Concurrence *int `json:"concurrence,omitempty"`
}

// DosageHistory defines model for DosageHistory.
type DosageHistory = []DosageObservation

// DosageHistoryCSV The CSV format of the user's dosage history.
type DosageHistoryCSV = string

// DosageObservation defines model for DosageObservation.
type DosageObservation struct {
	// ID The unique identifier for the observation.
	ID int64 `json:"id"`

	// DeliveryMethod The delivery method used.
	DeliveryMethod string `json:"deliveryMethod"`

	// Dose The dosage amount.
	Dose float32 `json:"dose"`

	// TakenAt The time the dosage was taken.
	TakenAt time.Time `json:"takenAt"`

	// TakenOffAt The time the dosage was taken off. This is only relevant for patch delivery methods.
	TakenOffAt *time.Time `json:"takenOffAt,omitempty"`

	// Comment A comment about the dosage, if any.
	Comment *string `json:"comment,omitempty"`
}

// DosageParams defines parameters for Dosage.
type DosageParams struct {
	Start *time.Time `form:"start,omitempty" json:"start,omitempty"`
	End   *time.Time `form:"end,omitempty" json:"end,omitempty"`
}

// ForgetDosesParams defines parameters for ForgetDoses.
type ForgetDosesParams struct {
	DoseIds []int64 `form:"dose_ids" json:"dose_ids"`
}

// EditDoseJSONBody defines parameters for EditDose.
type EditDoseJSONBody = DosageObservation

// ExportDosageHistoryParams defines parameters for ExportDosageHistory.
type ExportDosageHistoryParams struct {
	Start *time.Time `form:"start,omitempty" json:"start,omitempty"`
	End   *time.Time `form:"end,omitempty" json:"end,omitempty"`

	// Accept The format to export the dosage history in.
	Accept ExportDosageHistoryParamsAccept `json:"Accept"`
}

// ExportDosageHistoryParamsAccept defines parameters for ExportDosageHistory.
type ExportDosageHistoryParamsAccept string

// ImportDosageHistoryParams defines parameters for ImportDosageHistory.
type ImportDosageHistoryParams struct {
	// ContentType The format to import the dosage history as.
	ContentType ImportDosageHistoryParamsContentType `json:"Content-Type"`
}

// ImportDosageHistoryParamsContentType defines parameters for ImportDosageHistory.
type ImportDosageHistoryParamsContentType string

// SetDosageJSONRequestBody defines body for SetDosage for application/json ContentType.
type SetDosageJSONRequestBody = Dosage

// EditDoseJSONRequestBody defines body for EditDose for application/json ContentType.
type EditDoseJSONRequestBody = EditDoseJSONBody

// ImportDosageHistoryJSONRequestBody defines body for ImportDosageHistory for application/json ContentType.
type ImportDosageHistoryJSONRequestBody = DosageHistory
