# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/ba055ca00cbd735dceef4ed7c9db024cd9bfcd1a/schemas/v3.0/schema.json
openapi: 3.0.0

info:
  title: e2clicker service
  version: "0"

servers:
  - url: https://e2clicker.app/api
  - url: /api

paths: {}

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          description: A message describing the error
        details:
          description: Additional details about the error
        internal:
          type: boolean
          description: Whether the error is internal
        internalCode:
          type: string
          description: An internal code for the error (useless for clients)
      required: [message]

  responses:
    ErrorResponse:
      description: |
        The request is invalid.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

security:
  - bearerAuth: []
