# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/ba055ca00cbd735dceef4ed7c9db024cd9bfcd1a/schemas/v3.0/schema.json
openapi: 3.0.0

info:
  title: dosage
  version: ""

paths:
  /deliverymethods:
    get:
      summary: List all available delivery methods
      operationId: deliveryMethods
      security: []
      responses:
        "200":
          description: >-
            Successfully retrieved delivery methods.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DeliveryMethod"
        default:
          $ref: "./_base.yml#/components/responses/ErrorResponse"

  /dosage:
    get:
      summary: Get the user's dosage and optionally their history
      operationId: dosage
      parameters:
        - name: historyStart
          in: query
          schema:
            type: string
            format: date-time
            description: >-
              The start date of the history to retrieve, if requested.
        - name: historyEnd
          in: query
          schema:
            type: string
            format: date-time
            description: >-
              The end date of the history to retrieve, if requested.
      responses:
        "200":
          description: >-
            Successfully retrieved the dosage, if set.
          content:
            application/json:
              schema:
                properties:
                  dosage:
                    description: >-
                      The user's current dosage schedule.
                      This is null if the user has no dosage set.
                    allOf:
                      - $ref: "#/components/schemas/Dosage"
                  history:
                    description: >-
                      The user's dosage history within the requested time range.
                      If either historyStart or historyEnd are not provided, this will be null.
                    allOf:
                      - $ref: "#/components/schemas/DosageHistory"
    put:
      summary: Set the user's dosage
      operationId: setDosage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Dosage"
      responses:
        "204":
          description: >-
            Successfully set the dosage.
        default:
          $ref: "./_base.yml#/components/responses/ErrorResponse"
    delete:
      summary: Clear the user's dosage schedule
      operationId: clearDosage
      responses:
        "204":
          description: >-
            Successfully cleared the dosage.
        default:
          $ref: "./_base.yml#/components/responses/ErrorResponse"

  /dosage/dose:
    post:
      summary: Record a new dosage to the user's history
      operationId: recordDose
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [takenAt]
              properties:
                takenAt:
                  type: string
                  format: date-time
                  description: >-
                    The time the dosage was taken.
      responses:
        "200":
          description: >-
            Successfully recorded dosage.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DosageObservation"
    put:
      summary: Update a dosage in the user's history
      operationId: editDose
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: >-
                The updated dosage observation.
                The ID must match an existing observation.
              allOf:
                - $ref: "#/components/schemas/DosageObservation"
      responses:
        "204":
          description: >-
            Successfully updated dosage.
        default:
          $ref: "./_base.yml#/components/responses/ErrorResponse"
    delete:
      summary: Delete multiple dosages from the user's history
      operationId: forgetDoses
      parameters:
        - name: dose_ids
          in: query
          schema:
            type: array
            items:
              type: integer
              format: int64
              description: >-
                The dose IDs of the observations to delete.
          required: true
      responses:
        "204":
          description: >-
            Successfully deleted dosages.
        default:
          $ref: "./_base.yml#/components/responses/ErrorResponse"

components:
  schemas:
    DeliveryMethod:
      type: object
      required: [id, units, name]
      properties:
        id:
          type: string
          description: >-
            A short string representing the delivery method.
            This is what goes into the DeliveryMethod fields.
          x-order: 1
        units:
          type: string
          description: >-
            The units of the delivery method.
          x-order: 2
        name:
          type: string
          description: >-
            The full name of the delivery method.
          x-order: 3
        description:
          type: string
          description: >-
            A description of the delivery method.
          x-order: 4
          x-go-type-skip-optional-pointer: true

    Dosage:
      type: object
      required: [deliveryMethod, dose, interval]
      properties:
        deliveryMethod:
          type: string
          description: >-
            The delivery method to use.
          x-order: 1
        dose:
          type: number
          format: float
          description: >-
            The dosage amount.
          x-order: 2
        interval:
          type: number
          format: double
          description: >-
            The interval between doses in days.
          x-order: 3
        concurrence:
          type: integer
          description: >-
            The number of estrogen patches on the body at once.
            Only relevant if delivery method is patch.
          x-order: 4

    DosageHistory:
      type: array
      items:
        $ref: "#/components/schemas/DosageObservation"

    DosageObservation:
      type: object
      required: [id, deliveryMethod, dose, takenAt]
      properties:
        id:
          type: integer
          format: int64
          description: >-
            The unique identifier for the observation.
          x-order: 1
        deliveryMethod:
          type: string
          description: >-
            The delivery method used.
          x-order: 2
        dose:
          type: number
          format: float
          description: >-
            The dosage amount.
          x-order: 3
        takenAt:
          type: string
          format: date-time
          description: >-
            The time the dosage was taken.
          x-order: 4
        takenOffAt:
          type: string
          format: date-time
          description: >-
            The time the dosage was taken off.
            This is only relevant for patch delivery methods.
          x-order: 5
        comment:
          type: string
          description: >-
            A comment about the dosage, if any.
          x-order: 6
