# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/ba055ca00cbd735dceef4ed7c9db024cd9bfcd1a/schemas/v3.0/schema.json
openapi: 3.0.0

info:
  title: user
  version: ""

paths:
  /delivery-methods:
    get:
      summary: List all available delivery methods
      operationId: deliveryMethods
      security: []
      responses:
        "200":
          description: >-
            Successfully retrieved delivery methods.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DeliveryMethod"
        default:
          $ref: "#/components/responses/ErrorResponse"

  /dosage/schedule:
    get:
      summary: Get the user's dosage schedule
      operationId: dosageSchedule
      responses:
        "200":
          description: >-
            Successfully retrieved dosage schedule.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DosageSchedule"
    put:
      summary: Set the user's dosage schedule
      operationId: setDosageSchedule
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DosageSchedule"
      responses:
        "204":
          description: >-
            Successfully set dosage schedule.
        default:
          $ref: "#/components/responses/ErrorResponse"

  /dosage/history:
    get:
      summary: Get the user's dosage history within a time range
      operationId: doseHistory
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required: [start, end]
              properties:
                start:
                  type: string
                  format: date-time
                  description: >-
                    The start date of the history to retrieve.
                end:
                  type: string
                  format: date-time
                  description: >-
                    The end date of the history to retrieve.
      responses:
        "200":
          description: >-
            Successfully retrieved dosage history.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DosageHistory"
        default:
          $ref: "#/components/responses/ErrorResponse"
    post:
      summary: Record a new dosage to the user's history
      operationId: recordDose
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [takenAt]
              properties:
                takenAt:
                  type: string
                  format: date-time
                  description: >-
                    The time the dosage was taken.
      responses:
        "200":
          description: >-
            Successfully recorded dosage.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DosageObservation"
    put:
      summary: Update a dosage in the user's history
      operationId: editDose
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DosageObservation"
      responses:
        "204":
          description: >-
            Successfully updated dosage.
        default:
          $ref: "#/components/responses/ErrorResponse"
    delete:
      summary: Delete multiple dosages from the user's history
      operationId: forgetDoses
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [dose_ids]
              properties:
                dose_ids:
                  type: array
                  items:
                    type: integer
                    format: int64
                    description: >-
                      The dose IDs of the observations to delete.
      responses:
        "204":
          description: >-
            Successfully deleted dosages.
        default:
          $ref: "#/components/responses/ErrorResponse"

components:
  schemas:
    DeliveryMethod:
      type: object
      required: [id, units, name]
      properties:
        id:
          type: string
          description: >-
            A short string representing the delivery method.
            This is what goes into the DeliveryMethod fields.
          x-order: 1
        units:
          type: string
          description: >-
            The units of the delivery method.
          x-order: 2
        name:
          type: string
          description: >-
            The full name of the delivery method.
          x-order: 3

    DosageSchedule:
      type: object
      required: [deliveryMethod, dose, interval]
      properties:
        deliveryMethod:
          type: string
          description: >-
            The delivery method to use.
          x-order: 1
        dose:
          type: number
          format: float
          description: >-
            The dosage amount.
          x-order: 2
        interval:
          type: number
          format: double
          description: >-
            The interval between doses in days.
          x-order: 3
        concurrence:
          type: integer
          description: >-
            The number of estrogen patches on the body at once.
            Only relevant if delivery method is patch.
          x-order: 4

    DosageHistory:
      type: array
      items:
        $ref: "#/components/schemas/DosageObservation"

    DosageObservation:
      type: object
      required: [id, deliveryMethod, dose, takenAt]
      properties:
        id:
          type: integer
          format: int64
          description: >-
            The unique identifier for the observation.
          x-order: 1
        deliveryMethod:
          type: string
          description: >-
            The delivery method used.
          x-order: 2
        dose:
          type: number
          format: float
          description: >-
            The dosage amount.
          x-order: 3
        takenAt:
          type: string
          format: date-time
          description: >-
            The time the dosage was taken.
          x-order: 4
        takenOffAt:
          type: string
          format: date-time
          description: >-
            The time the dosage was taken off.
            This is only relevant for patch delivery methods.
          x-order: 5
