# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/ba055ca00cbd735dceef4ed7c9db024cd9bfcd1a/schemas/v3.0/schema.json
openapi: 3.0.0

info:
  title: dosage
  version: ""

paths:
  /delivery-methods:
    get:
      summary: List all available delivery methods
      operationId: deliveryMethods
      security: []
      responses:
        "200":
          description: >-
            Successfully retrieved delivery methods.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DeliveryMethod"
        default:
          $ref: "./_base.yml#/components/responses/ErrorResponse"

  /dosage:
    get:
      summary: Get the user's dosage and optionally their history
      operationId: dosage
      parameters:
        - name: start
          in: query
          schema:
            type: string
            format: date-time
            description: >-
              The start date of the history to retrieve, if requested.
        - name: end
          in: query
          schema:
            type: string
            format: date-time
            description: >-
              The end date of the history to retrieve, if requested.
      responses:
        "200":
          description: >-
            Successfully retrieved the dosage, if set.
          content:
            application/json:
              schema:
                properties:
                  dosage:
                    description: >-
                      The user's current dosage schedule.
                      This is null if the user has no dosage set.
                    allOf:
                      - $ref: "#/components/schemas/Dosage"
                  history:
                    description: >-
                      The user's dosage history within the requested time range.
                      If either historyStart or historyEnd are not provided, this will be null.
                    allOf:
                      - $ref: "#/components/schemas/DosageHistory"
    put:
      summary: Set the user's dosage
      operationId: setDosage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Dosage"
      responses:
        "204":
          description: >-
            Successfully set the dosage.
        default:
          $ref: "./_base.yml#/components/responses/ErrorResponse"
    delete:
      summary: Clear the user's dosage schedule
      operationId: clearDosage
      responses:
        "204":
          description: >-
            Successfully cleared the dosage.
        default:
          $ref: "./_base.yml#/components/responses/ErrorResponse"

  /dosage/dose:
    post:
      summary: Record a new dosage to the user's history
      operationId: recordDose
      description: >-
        This endpoint is used to record a new dosage observation to the user's
        history. The current time is automatically used.
      responses:
        "200":
          description: >-
            Successfully recorded dosage.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dose"
    delete:
      summary: Delete multiple dosages from the user's history
      operationId: forgetDoses
      parameters:
        - name: doseTimes
          in: query
          schema:
            type: array
            items:
              type: string
              format: date-time
              description: >-
                The times the dosages were taken that should be deleted.
          required: true
      responses:
        "204":
          description: >-
            Successfully deleted dosages.
        default:
          $ref: "./_base.yml#/components/responses/ErrorResponse"

  /dosage/dose/{doseTime}:
    put:
      summary: Update a dosage in the user's history
      operationId: editDose
      parameters:
        - in: path
          name: doseTime
          schema:
            type: string
            format: date-time
            description: >-
              The time the dosage was taken.
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: >-
                The updated dosage observation.
              allOf:
                - $ref: "#/components/schemas/Dose"
      responses:
        "204":
          description: >-
            Successfully updated the dosage.
        default:
          $ref: "./_base.yml#/components/responses/ErrorResponse"
    delete:
      summary: Delete a dosage from the user's history
      operationId: forgetDose
      parameters:
        - in: path
          name: doseTime
          schema:
            type: string
            format: date-time
            description: >-
              The time the dosage was taken.
          required: true
      responses:
        "204":
          description: >-
            Successfully deleted the dosage.
        default:
          $ref: "./_base.yml#/components/responses/ErrorResponse"

  /dosage/export-doses:
    get:
      summary: Export the user's dosage history
      operationId: exportDoses
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
            enum: [text/csv, application/json]
            default: text/csv
          required: true
          description: >-
            The format to export the dosage history in.
        - name: start
          in: query
          schema:
            type: string
            format: date-time
            description: >-
              The start date of the history to retrieve.
              If not provided, defaults to the beginning of time.
        - name: end
          in: query
          schema:
            type: string
            format: date-time
            description: >-
              The end date of the history to retrieve.
              If not provided, defaults to the current time.
      responses:
        "200":
          description: >-
            Successfully retrieved the dosage history.
          headers:
            Content-Disposition:
              schema:
                type: string
                description: >-
                  The filename to use when saving the file.
          content:
            text/csv:
              schema:
                $ref: "#/components/schemas/DosageHistoryCSV"
            application/json:
              schema:
                $ref: "#/components/schemas/DosageHistory"
        "429":
          $ref: "./_base.yml#/components/responses/RateLimitedResponse"
        default:
          $ref: "./_base.yml#/components/responses/ErrorResponse"

  /dosage/import-doses:
    post:
      summary: Import a CSV file of dosage history
      operationId: importDoses
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
            enum: [text/csv, application/json]
            default: text/csv
          required: true
          description: >-
            The format to import the dosage history as.
      requestBody:
        required: true
        content:
          text/csv:
            schema:
              $ref: "#/components/schemas/DosageHistoryCSV"
          application/json:
            schema:
              $ref: "#/components/schemas/DosageHistory"
      responses:
        "200":
          description: >-
            Successfully imported the dosage history.
          content:
            application/json:
              schema:
                required: [records, succeeded]
                properties:
                  records:
                    type: integer
                    description: >-
                      The number of records in the file.
                  succeeded:
                    type: integer
                    description: >-
                      The number of records actually imported successfully. This
                      is not equal to #records if there were errors or duplicate
                      entries.
                  error:
                    $ref: "./_base.yml#/components/schemas/Error"

components:
  schemas:
    DeliveryMethod:
      type: object
      required: [id, units, name]
      properties:
        id:
          type: string
          description: >-
            A short string representing the delivery method.
            This is what goes into the DeliveryMethod fields.
          x-order: 1
        units:
          type: string
          description: >-
            The units of the delivery method.
          x-order: 2
        name:
          type: string
          description: >-
            The full name of the delivery method.
          x-order: 3
        description:
          type: string
          description: >-
            A description of the delivery method.
          x-order: 4
          x-go-type-skip-optional-pointer: true

    Dosage:
      type: object
      required: [deliveryMethod, dose, interval]
      properties:
        deliveryMethod:
          type: string
          description: >-
            The delivery method to use.
          x-order: 1
        dose:
          type: number
          format: float
          description: >-
            The dosage amount.
          x-order: 2
        interval:
          type: number
          format: double
          description: >-
            The interval between doses in days.
          x-order: 3
        concurrence:
          type: integer
          description: >-
            The number of estrogen patches on the body at once.
            Only relevant if delivery method is patch.
          x-order: 4

    DosageHistory:
      type: array
      items:
        $ref: "#/components/schemas/Dose"

    DosageHistoryCSV:
      type: string
      example: |-
        dose,method,takenAt,takenOffAt,comment
        100,patch tw,2020-01-01T00:00:00Z,,
        100,patch tw,2020-01-02T12:00:00Z,,
        100,patch tw,2020-01-04T00:00:00Z,,
        100,patch tw,2020-01-05T12:00:00Z,,
      description: >-
        The CSV format of the user's dosage history.

    Dose:
      description: >-
        A dose of medication in time.
      type: object
      required: [deliveryMethod, dose, takenAt]
      properties:
        deliveryMethod:
          type: string
          description: >-
            The delivery method used.
          x-order: 2
        dose:
          type: number
          format: float
          description: >-
            The dosage amount.
          x-order: 3
        takenAt:
          type: string
          format: date-time
          description: >-
            The time the dosage was taken.
          x-order: 4
        takenOffAt:
          type: string
          format: date-time
          description: >-
            The time the dosage was taken off.
            This is only relevant for patch delivery methods.
          x-order: 5
        comment:
          type: string
          description: >-
            A comment about the dosage, if any.
          x-order: 6
