# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/ba055ca00cbd735dceef4ed7c9db024cd9bfcd1a/schemas/v3.0/schema.json
openapi: 3.0.0

info:
  title: notification
  version: ""

paths:
  /pushinfo:
    get:
      summary: Get the server's push notification information
      operationId: webPushInfo
      security: []
      responses:
        "200":
          description: >-
            Successfully retrieved the server's push notification information.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PushInfo"
        default:
          $ref: "./_base.yml#/components/responses/ErrorResponse"

  /notifications/methods:
    get:
      summary: Get the user's notification methods
      operationId: userNotificationMethods
      responses:
        "200":
          description: >-
            Successfully retrieved the user's push notification subscription.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReturnedNotificationMethods"
        default:
          $ref: "./_base.yml#/components/responses/ErrorResponse"

  /notifications/methods/push/{deviceID}:
    get:
      summary: Get the user's push notification subscription
      operationId: userPushSubscription
      parameters:
        - name: deviceID
          in: path
          schema:
            $ref: "#/components/schemas/PushDeviceID"
          required: true
          description: >-
            The device ID of the push subscription to retrieve.
      responses:
        "200":
          description: >-
            Successfully retrieved the user's push notification subscription.
            The returned object will contain secrets.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PushSubscription"
        "404":
          description: >-
            The user does not have a push notification subscription for the
            specified device ID.
          content:
            application/json:
              schema:
                $ref: "./_base.yml#/components/schemas/Error"
        default:
          $ref: "./_base.yml#/components/responses/ErrorResponse"
    delete:
      summary: Unsubscribe from push notifications
      operationId: userUnsubscribePush
      parameters:
        - name: deviceID
          in: path
          schema:
            $ref: "#/components/schemas/PushDeviceID"
          required: true
          description: >-
            The device ID of the push subscription to unsubscribe from.
      responses:
        "204":
          description: >-
            Successfully unsubscribed from push notifications.
        default:
          $ref: "./_base.yml#/components/responses/ErrorResponse"

  /notifications/methods/push:
    put:
      summary: Create or update a push subscription
      operationId: userSubscribePush
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PushSubscription"
      responses:
        "204":
          description: >-
            Successfully subscribed to push notifications.
        default:
          $ref: "./_base.yml#/components/responses/ErrorResponse"

components:
  schemas:
    Notification:
      required: [type, message, username]
      properties:
        type:
          type: string
          enum:
            - reminder
            - account_notice
            - web_push_expiring
          description: >-
            The type of notification.
          x-order: 1
        message:
          description: >-
            The message of the notification.
          allOf:
            - $ref: "#/components/schemas/NotificationMessage"
          x-order: 2
        username:
          type: string
          description: >-
            The username of the user to send the notification to.
          x-order: 3

    NotificationMessage:
      description: >-
        The message of the notification.
        This is derived from the notification type but can be overridden by
        the user.
      required: [title, message]
      properties:
        title:
          type: string
          description: >-
            The title of the notification.
          x-order: 1
        message:
          type: string
          description: >-
            The message of the notification.
          x-order: 2

    PushDeviceID:
      type: string
      example: 7996e974
      description: >-
        A short ID associated with the device that the push subscription is for
        This is used to identify the device when updating its push subscription
        later on.

        Realistically, this will be handled as an opaque random string
        generated on the device side, so the server has no way to correlate 
        it with any fingerprinting.

        The recommended way to generate this string in JavaScript is:

        ```js
        crypto.randomUUID().slice(0, 8)
        ```
      x-order: -99

    PushInfo:
      description: >-
        This is returned by the server and contains information that the client
        would need to subscribe to push notifications.
      required: [applicationServerKey]
      properties:
        applicationServerKey:
          type: string
          description: >-
            A Base64-encoded string or ArrayBuffer containing an ECDSA P-256
            public key that the push server will use to authenticate your
            application server. If specified, all messages from your application
            server must use the VAPID authentication scheme, and include a JWT
            signed with the corresponding private key. This key IS NOT the same
            ECDH key that you use to encrypt the data. For more information, see
            "Using VAPID with WebPush".

    PushSubscription:
      description: >-
        The configuration for a push notification subscription.

        This is the object that is returned by calling
        PushSubscription.toJSON(). More information can be found at:
        https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription/toJSON
      required: [deviceID, endpoint, keys]
      properties:
        deviceID:
          $ref: "#/components/schemas/PushDeviceID"
        endpoint:
          type: string
          description: >-
            The endpoint to send the notification to.
          x-order: 1
        expirationTime:
          type: string
          format: date-time
          description: >-
            The time at which the subscription expires. This is the time when
            the subscription will be automatically deleted by the browser.
          x-order: 2
        keys:
          type: object
          description: >-
            The VAPID keys to encrypt the push notification.
          required: [p256dh, auth]
          properties:
            p256dh:
              type: string
              description: >-
                An Elliptic curve Diffie–Hellman public key on the P-256 curve
                (that is, the NIST secp256r1 elliptic curve). The resulting key
                is an uncompressed point in ANSI X9.62 format.
              x-order: 1
            auth:
              type: string
              description: >-
                An authentication secret, as described in Message Encryption for
                Web Push.
              x-order: 2
          x-order: 3

    ReturnedNotificationMethods:
      properties:
        webPush:
          type: array
          items:
            $ref: "#/components/schemas/ReturnedPushSubscription"
        # TODO: email
        # TODO: gotify
        # TODO: pushover

    ReturnedPushSubscription:
      description: >-
        Similar to a [PushSubscription], but specifically for returning to the user.
        This type contains no secrets.
      required: [deviceID, keys]
      properties:
        deviceID:
          allOf:
            - $ref: "#/components/schemas/PushDeviceID"
          x-order: 1
        expirationTime:
          type: string
          format: date-time
          description: >-
            The time at which the subscription expires. This is the time when
            the subscription will be automatically deleted by the browser.
        keys:
          required: [p256dh]
          properties:
            p256dh:
              type: string
              description: >-
                An Elliptic curve Diffie–Hellman public key on the P-256 curve
                (that is, the NIST secp256r1 elliptic curve). The resulting key
                is an uncompressed point in ANSI X9.62 format.
          x-order: 2
