//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version (devel) DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	"libdb.so/e2clicker/services/user"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for NotificationType.
const (
	AccountNotice   NotificationType = "account_notice"
	Reminder        NotificationType = "reminder"
	WebPushExpiring NotificationType = "web_push_expiring"
)

// DeliveryMethod defines model for DeliveryMethod.
type DeliveryMethod struct {
	// ID A short string representing the delivery method. This is what goes into the DeliveryMethod fields.
	ID string `json:"id"`

	// Units The units of the delivery method.
	Units string `json:"units"`

	// Name The full name of the delivery method.
	Name string `json:"name"`
}

// Dosage defines model for Dosage.
type Dosage struct {
	// DeliveryMethod The delivery method to use.
	DeliveryMethod string `json:"deliveryMethod"`

	// Dose The dosage amount.
	Dose float32 `json:"dose"`

	// Interval The interval between doses in days.
	Interval float64 `json:"interval"`

	// Concurrence The number of estrogen patches on the body at once. Only relevant if delivery method is patch.
	Concurrence *int `json:"concurrence,omitempty"`
}

// DosageHistory defines model for DosageHistory.
type DosageHistory = []DosageObservation

// DosageObservation defines model for DosageObservation.
type DosageObservation struct {
	// ID The unique identifier for the observation.
	ID int64 `json:"id"`

	// DeliveryMethod The delivery method used.
	DeliveryMethod string `json:"deliveryMethod"`

	// Dose The dosage amount.
	Dose float32 `json:"dose"`

	// TakenAt The time the dosage was taken.
	TakenAt time.Time `json:"takenAt"`

	// TakenOffAt The time the dosage was taken off. This is only relevant for patch delivery methods.
	TakenOffAt *time.Time `json:"takenOffAt,omitempty"`

	// Comment A comment about the dosage, if any.
	Comment *string `json:"comment,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Details Additional details about the error
	Details *interface{} `json:"details,omitempty"`

	// Internal Whether the error is internal
	Internal *bool `json:"internal,omitempty"`

	// InternalCode An internal code for the error (useless for clients)
	InternalCode *string `json:"internalCode,omitempty"`

	// Message A message describing the error
	Message string `json:"message"`
}

// Locale A locale identifier.
type Locale = user.Locale

// Notification defines model for Notification.
type Notification struct {
	// Type The type of notification.
	Type NotificationType `json:"type"`

	// Message The message of the notification.
	Message NotificationMessage `json:"message"`

	// Username The username of the user to send the notification to.
	Username string `json:"username"`
}

// NotificationType The type of notification.
type NotificationType string

// NotificationMessage The message of the notification. This is derived from the notification type but can be overridden by the user.
type NotificationMessage struct {
	// Title The title of the notification.
	Title string `json:"title"`

	// Message The message of the notification.
	Message string `json:"message"`
}

// PushInfo This is returned by the server and contains information that the client would need to subscribe to push notifications.
type PushInfo struct {
	// ApplicationServerKey A Base64-encoded string or ArrayBuffer containing an ECDSA P-256 public key that the push server will use to authenticate your application server. If specified, all messages from your application server must use the VAPID authentication scheme, and include a JWT signed with the corresponding private key. This key IS NOT the same ECDH key that you use to encrypt the data. For more information, see "Using VAPID with WebPush".
	ApplicationServerKey *[]byte `json:"applicationServerKey,omitempty"`
}

// PushSubscription The configuration for a push notification subscription.
// This is the object that is returned by calling PushSubscription.toJSON(). More information can be found at: https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription/toJSON
type PushSubscription struct {
	// Endpoint The endpoint to send the notification to.
	Endpoint string `json:"endpoint"`

	// ExpirationTime The time in milliseconds at which the subscription expires. This is the time when the subscription will be automatically deleted by the browser.
	ExpirationTime *float64 `json:"expirationTime,omitempty"`

	// Keys The VAPID keys to encrypt the push notification.
	Keys struct {
		// P256Dh An Elliptic curve Diffie–Hellman public key on the P-256 curve (that is, the NIST secp256r1 elliptic curve). The resulting key is an uncompressed point in ANSI X9.62 format.
		P256Dh string `json:"p256dh"`

		// Auth An authentication secret, as described in Message Encryption for Web Push.
		Auth string `json:"auth"`
	} `json:"keys"`
}

// Session A session for a user.
type Session struct {
	// ID The session identifier
	ID int64 `json:"id"`

	// CreatedAt The time the session was created
	CreatedAt time.Time `json:"createdAt"`

	// LastUsed The last time the session was used
	LastUsed time.Time `json:"lastUsed"`

	// ExpiresAt The time the session expires, or null if it never expires
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

// User A user of the system.
type User struct {
	// Name The user's name
	Name string `json:"name"`

	// Locale A locale identifier.
	Locale Locale `json:"locale"`

	// HasAvatar Whether the user has an avatar.
	HasAvatar bool `json:"hasAvatar"`
}

// UserSecret A secret and unique user identifier. This secret is generated once and never changes. It is used to both authenticate and identify a user, so it should be kept secret.
type UserSecret = user.Secret

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = Error

// AuthJSONBody defines parameters for Auth.
type AuthJSONBody struct {
	// Secret A secret and unique user identifier. This secret is generated once and never changes. It is used to both authenticate and identify a user, so it should be kept secret.
	Secret UserSecret `json:"secret"`
}

// AuthParams defines parameters for Auth.
type AuthParams struct {
	// UserAgent The user agent of the client making the request.
	UserAgent *string `json:"User-Agent,omitempty"`
}

// DosageParams defines parameters for Dosage.
type DosageParams struct {
	HistoryStart *time.Time `form:"historyStart,omitempty" json:"historyStart,omitempty"`
	HistoryEnd   *time.Time `form:"historyEnd,omitempty" json:"historyEnd,omitempty"`
}

// ForgetDosesParams defines parameters for ForgetDoses.
type ForgetDosesParams struct {
	DoseIds []int64 `form:"dose_ids" json:"dose_ids"`
}

// RecordDoseJSONBody defines parameters for RecordDose.
type RecordDoseJSONBody struct {
	// TakenAt The time the dosage was taken.
	TakenAt time.Time `json:"takenAt"`
}

// EditDoseJSONBody defines parameters for EditDose.
type EditDoseJSONBody = DosageObservation

// DeleteUserSessionJSONBody defines parameters for DeleteUserSession.
type DeleteUserSessionJSONBody struct {
	// ID The session identifier to delete
	ID int64 `json:"id"`
}

// RegisterJSONBody defines parameters for Register.
type RegisterJSONBody struct {
	// Name The name to register with
	Name string `json:"name"`
}

// AuthJSONRequestBody defines body for Auth for application/json ContentType.
type AuthJSONRequestBody AuthJSONBody

// SetDosageJSONRequestBody defines body for SetDosage for application/json ContentType.
type SetDosageJSONRequestBody = Dosage

// RecordDoseJSONRequestBody defines body for RecordDose for application/json ContentType.
type RecordDoseJSONRequestBody RecordDoseJSONBody

// EditDoseJSONRequestBody defines body for EditDose for application/json ContentType.
type EditDoseJSONRequestBody = EditDoseJSONBody

// DeleteUserSessionJSONRequestBody defines body for DeleteUserSession for application/json ContentType.
type DeleteUserSessionJSONRequestBody DeleteUserSessionJSONBody

// UserSubscribePushJSONRequestBody defines body for UserSubscribePush for application/json ContentType.
type UserSubscribePushJSONRequestBody = PushSubscription

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody RegisterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate a user and obtain a session
	// (POST /auth)
	Auth(w http.ResponseWriter, r *http.Request, params AuthParams)
	// List all available delivery methods
	// (GET /delivery-methods)
	DeliveryMethods(w http.ResponseWriter, r *http.Request)
	// Clear the user's dosage schedule
	// (DELETE /dosage)
	ClearDosage(w http.ResponseWriter, r *http.Request)
	// Get the user's dosage and optionally their history
	// (GET /dosage)
	Dosage(w http.ResponseWriter, r *http.Request, params DosageParams)
	// Set the user's dosage
	// (PUT /dosage)
	SetDosage(w http.ResponseWriter, r *http.Request)
	// Delete multiple dosages from the user's history
	// (DELETE /dosage/dose)
	ForgetDoses(w http.ResponseWriter, r *http.Request, params ForgetDosesParams)
	// Record a new dosage to the user's history
	// (POST /dosage/dose)
	RecordDose(w http.ResponseWriter, r *http.Request)
	// Update a dosage in the user's history
	// (PUT /dosage/dose)
	EditDose(w http.ResponseWriter, r *http.Request)
	// Get the current user
	// (GET /me)
	CurrentUser(w http.ResponseWriter, r *http.Request)
	// Get the current user's avatar
	// (GET /me/avatar)
	CurrentUserAvatar(w http.ResponseWriter, r *http.Request)
	// Set the current user's avatar
	// (PUT /me/avatar)
	SetCurrentUserAvatar(w http.ResponseWriter, r *http.Request)
	// Get the current user's secret
	// (GET /me/secret)
	CurrentUserSecret(w http.ResponseWriter, r *http.Request)
	// Delete one of the current user's sessions
	// (DELETE /me/sessions)
	DeleteUserSession(w http.ResponseWriter, r *http.Request)
	// List the current user's sessions
	// (GET /me/sessions)
	CurrentUserSessions(w http.ResponseWriter, r *http.Request)
	// Get the server's push notification information
	// (GET /notification/push)
	PushInfo(w http.ResponseWriter, r *http.Request)
	// Unsubscribe from push notifications
	// (DELETE /notification/push/subscription)
	UserUnsubscribePush(w http.ResponseWriter, r *http.Request)
	// Get the user's push notification subscription
	// (GET /notification/push/subscription)
	UserPushSubscription(w http.ResponseWriter, r *http.Request)
	// Subscribe to push notifications
	// (POST /notification/push/subscription)
	UserSubscribePush(w http.ResponseWriter, r *http.Request)
	// Register a new account
	// (POST /register)
	Register(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Auth operation middleware
func (siw *ServerInterfaceWrapper) Auth(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AuthParams

	headers := r.Header

	// ------------- Optional header parameter "User-Agent" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("User-Agent")]; found {
		var UserAgent string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "User-Agent", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "User-Agent", valueList[0], &UserAgent, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "User-Agent", Err: err})
			return
		}

		params.UserAgent = &UserAgent

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Auth(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeliveryMethods operation middleware
func (siw *ServerInterfaceWrapper) DeliveryMethods(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeliveryMethods(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClearDosage operation middleware
func (siw *ServerInterfaceWrapper) ClearDosage(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClearDosage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Dosage operation middleware
func (siw *ServerInterfaceWrapper) Dosage(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DosageParams

	// ------------- Optional query parameter "historyStart" -------------

	err = runtime.BindQueryParameter("form", true, false, "historyStart", r.URL.Query(), &params.HistoryStart)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "historyStart", Err: err})
		return
	}

	// ------------- Optional query parameter "historyEnd" -------------

	err = runtime.BindQueryParameter("form", true, false, "historyEnd", r.URL.Query(), &params.HistoryEnd)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "historyEnd", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Dosage(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetDosage operation middleware
func (siw *ServerInterfaceWrapper) SetDosage(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetDosage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ForgetDoses operation middleware
func (siw *ServerInterfaceWrapper) ForgetDoses(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ForgetDosesParams

	// ------------- Required query parameter "dose_ids" -------------

	if paramValue := r.URL.Query().Get("dose_ids"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "dose_ids"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "dose_ids", r.URL.Query(), &params.DoseIds)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dose_ids", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ForgetDoses(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecordDose operation middleware
func (siw *ServerInterfaceWrapper) RecordDose(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecordDose(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EditDose operation middleware
func (siw *ServerInterfaceWrapper) EditDose(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EditDose(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CurrentUser operation middleware
func (siw *ServerInterfaceWrapper) CurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CurrentUserAvatar operation middleware
func (siw *ServerInterfaceWrapper) CurrentUserAvatar(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CurrentUserAvatar(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetCurrentUserAvatar operation middleware
func (siw *ServerInterfaceWrapper) SetCurrentUserAvatar(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetCurrentUserAvatar(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CurrentUserSecret operation middleware
func (siw *ServerInterfaceWrapper) CurrentUserSecret(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CurrentUserSecret(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUserSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUserSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CurrentUserSessions operation middleware
func (siw *ServerInterfaceWrapper) CurrentUserSessions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CurrentUserSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PushInfo operation middleware
func (siw *ServerInterfaceWrapper) PushInfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PushInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UserUnsubscribePush operation middleware
func (siw *ServerInterfaceWrapper) UserUnsubscribePush(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserUnsubscribePush(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UserPushSubscription operation middleware
func (siw *ServerInterfaceWrapper) UserPushSubscription(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserPushSubscription(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UserSubscribePush operation middleware
func (siw *ServerInterfaceWrapper) UserSubscribePush(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserSubscribePush(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/auth", wrapper.Auth)
	m.HandleFunc("GET "+options.BaseURL+"/delivery-methods", wrapper.DeliveryMethods)
	m.HandleFunc("DELETE "+options.BaseURL+"/dosage", wrapper.ClearDosage)
	m.HandleFunc("GET "+options.BaseURL+"/dosage", wrapper.Dosage)
	m.HandleFunc("PUT "+options.BaseURL+"/dosage", wrapper.SetDosage)
	m.HandleFunc("DELETE "+options.BaseURL+"/dosage/dose", wrapper.ForgetDoses)
	m.HandleFunc("POST "+options.BaseURL+"/dosage/dose", wrapper.RecordDose)
	m.HandleFunc("PUT "+options.BaseURL+"/dosage/dose", wrapper.EditDose)
	m.HandleFunc("GET "+options.BaseURL+"/me", wrapper.CurrentUser)
	m.HandleFunc("GET "+options.BaseURL+"/me/avatar", wrapper.CurrentUserAvatar)
	m.HandleFunc("PUT "+options.BaseURL+"/me/avatar", wrapper.SetCurrentUserAvatar)
	m.HandleFunc("GET "+options.BaseURL+"/me/secret", wrapper.CurrentUserSecret)
	m.HandleFunc("DELETE "+options.BaseURL+"/me/sessions", wrapper.DeleteUserSession)
	m.HandleFunc("GET "+options.BaseURL+"/me/sessions", wrapper.CurrentUserSessions)
	m.HandleFunc("GET "+options.BaseURL+"/notification/push", wrapper.PushInfo)
	m.HandleFunc("DELETE "+options.BaseURL+"/notification/push/subscription", wrapper.UserUnsubscribePush)
	m.HandleFunc("GET "+options.BaseURL+"/notification/push/subscription", wrapper.UserPushSubscription)
	m.HandleFunc("POST "+options.BaseURL+"/notification/push/subscription", wrapper.UserSubscribePush)
	m.HandleFunc("POST "+options.BaseURL+"/register", wrapper.Register)

	return m
}

type ErrorResponseJSONResponse Error

type AuthRequestObject struct {
	Params AuthParams
	Body   *AuthJSONRequestBody
}

type AuthResponseObject interface {
	VisitAuthResponse(w http.ResponseWriter) error
}

type Auth200JSONResponse struct {
	// Token The session token
	Token string `json:"token"`
}

func (response Auth200JSONResponse) VisitAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AuthdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response AuthdefaultJSONResponse) VisitAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeliveryMethodsRequestObject struct {
}

type DeliveryMethodsResponseObject interface {
	VisitDeliveryMethodsResponse(w http.ResponseWriter) error
}

type DeliveryMethods200JSONResponse []DeliveryMethod

func (response DeliveryMethods200JSONResponse) VisitDeliveryMethodsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeliveryMethodsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeliveryMethodsdefaultJSONResponse) VisitDeliveryMethodsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ClearDosageRequestObject struct {
}

type ClearDosageResponseObject interface {
	VisitClearDosageResponse(w http.ResponseWriter) error
}

type ClearDosage204Response struct {
}

func (response ClearDosage204Response) VisitClearDosageResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ClearDosagedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ClearDosagedefaultJSONResponse) VisitClearDosageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DosageRequestObject struct {
	Params DosageParams
}

type DosageResponseObject interface {
	VisitDosageResponse(w http.ResponseWriter) error
}

type Dosage200JSONResponse struct {
	// Dosage The user's current dosage schedule. This is null if the user has no dosage set.
	Dosage *Dosage `json:"dosage,omitempty"`

	// History The user's dosage history within the requested time range. If either historyStart or historyEnd are not provided, this will be null.
	History *DosageHistory `json:"history,omitempty"`
}

func (response Dosage200JSONResponse) VisitDosageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SetDosageRequestObject struct {
	Body *SetDosageJSONRequestBody
}

type SetDosageResponseObject interface {
	VisitSetDosageResponse(w http.ResponseWriter) error
}

type SetDosage204Response struct {
}

func (response SetDosage204Response) VisitSetDosageResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SetDosagedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SetDosagedefaultJSONResponse) VisitSetDosageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ForgetDosesRequestObject struct {
	Params ForgetDosesParams
}

type ForgetDosesResponseObject interface {
	VisitForgetDosesResponse(w http.ResponseWriter) error
}

type ForgetDoses204Response struct {
}

func (response ForgetDoses204Response) VisitForgetDosesResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ForgetDosesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ForgetDosesdefaultJSONResponse) VisitForgetDosesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type RecordDoseRequestObject struct {
	Body *RecordDoseJSONRequestBody
}

type RecordDoseResponseObject interface {
	VisitRecordDoseResponse(w http.ResponseWriter) error
}

type RecordDose200JSONResponse DosageObservation

func (response RecordDose200JSONResponse) VisitRecordDoseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type EditDoseRequestObject struct {
	Body *EditDoseJSONRequestBody
}

type EditDoseResponseObject interface {
	VisitEditDoseResponse(w http.ResponseWriter) error
}

type EditDose204Response struct {
}

func (response EditDose204Response) VisitEditDoseResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type EditDosedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response EditDosedefaultJSONResponse) VisitEditDoseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CurrentUserRequestObject struct {
}

type CurrentUserResponseObject interface {
	VisitCurrentUserResponse(w http.ResponseWriter) error
}

type CurrentUser200JSONResponse User

func (response CurrentUser200JSONResponse) VisitCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CurrentUserdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CurrentUserdefaultJSONResponse) VisitCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CurrentUserAvatarRequestObject struct {
}

type CurrentUserAvatarResponseObject interface {
	VisitCurrentUserAvatarResponse(w http.ResponseWriter) error
}

type CurrentUserAvatar200ImageResponse struct {
	Body          io.Reader
	ContentType   string
	ContentLength int64
}

func (response CurrentUserAvatar200ImageResponse) VisitCurrentUserAvatarResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", response.ContentType)
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type CurrentUserAvatardefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CurrentUserAvatardefaultJSONResponse) VisitCurrentUserAvatarResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type SetCurrentUserAvatarRequestObject struct {
	ContentType string
	Body        io.Reader
}

type SetCurrentUserAvatarResponseObject interface {
	VisitSetCurrentUserAvatarResponse(w http.ResponseWriter) error
}

type SetCurrentUserAvatar204Response struct {
}

func (response SetCurrentUserAvatar204Response) VisitSetCurrentUserAvatarResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SetCurrentUserAvatardefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SetCurrentUserAvatardefaultJSONResponse) VisitSetCurrentUserAvatarResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CurrentUserSecretRequestObject struct {
}

type CurrentUserSecretResponseObject interface {
	VisitCurrentUserSecretResponse(w http.ResponseWriter) error
}

type CurrentUserSecret200JSONResponse struct {
	// Secret A secret and unique user identifier. This secret is generated once and never changes. It is used to both authenticate and identify a user, so it should be kept secret.
	Secret UserSecret `json:"secret"`
}

func (response CurrentUserSecret200JSONResponse) VisitCurrentUserSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CurrentUserSecretdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CurrentUserSecretdefaultJSONResponse) VisitCurrentUserSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteUserSessionRequestObject struct {
	Body *DeleteUserSessionJSONRequestBody
}

type DeleteUserSessionResponseObject interface {
	VisitDeleteUserSessionResponse(w http.ResponseWriter) error
}

type DeleteUserSession204Response struct {
}

func (response DeleteUserSession204Response) VisitDeleteUserSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteUserSessiondefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteUserSessiondefaultJSONResponse) VisitDeleteUserSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CurrentUserSessionsRequestObject struct {
}

type CurrentUserSessionsResponseObject interface {
	VisitCurrentUserSessionsResponse(w http.ResponseWriter) error
}

type CurrentUserSessions200JSONResponse []Session

func (response CurrentUserSessions200JSONResponse) VisitCurrentUserSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CurrentUserSessionsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CurrentUserSessionsdefaultJSONResponse) VisitCurrentUserSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PushInfoRequestObject struct {
}

type PushInfoResponseObject interface {
	VisitPushInfoResponse(w http.ResponseWriter) error
}

type PushInfo200JSONResponse PushInfo

func (response PushInfo200JSONResponse) VisitPushInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PushInfodefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response PushInfodefaultJSONResponse) VisitPushInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type UserUnsubscribePushRequestObject struct {
}

type UserUnsubscribePushResponseObject interface {
	VisitUserUnsubscribePushResponse(w http.ResponseWriter) error
}

type UserUnsubscribePush204Response struct {
}

func (response UserUnsubscribePush204Response) VisitUserUnsubscribePushResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UserUnsubscribePush404Response struct {
}

func (response UserUnsubscribePush404Response) VisitUserUnsubscribePushResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UserUnsubscribePushdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response UserUnsubscribePushdefaultJSONResponse) VisitUserUnsubscribePushResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type UserPushSubscriptionRequestObject struct {
}

type UserPushSubscriptionResponseObject interface {
	VisitUserPushSubscriptionResponse(w http.ResponseWriter) error
}

type UserPushSubscription200JSONResponse struct {
	// ExpirationTime The time at which the subscription expires. This is the time when the subscription will be automatically deleted by the browser.
	ExpirationTime *int `json:"expirationTime,omitempty"`
}

func (response UserPushSubscription200JSONResponse) VisitUserPushSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UserPushSubscription404Response struct {
}

func (response UserPushSubscription404Response) VisitUserPushSubscriptionResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UserPushSubscriptiondefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response UserPushSubscriptiondefaultJSONResponse) VisitUserPushSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type UserSubscribePushRequestObject struct {
	Body *UserSubscribePushJSONRequestBody
}

type UserSubscribePushResponseObject interface {
	VisitUserSubscribePushResponse(w http.ResponseWriter) error
}

type UserSubscribePush204Response struct {
}

func (response UserSubscribePush204Response) VisitUserSubscribePushResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UserSubscribePushdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response UserSubscribePushdefaultJSONResponse) VisitUserSubscribePushResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register200JSONResponse struct {
	// Name The user's name
	Name string `json:"name"`

	// Locale A locale identifier.
	Locale Locale `json:"locale"`

	// HasAvatar Whether the user has an avatar.
	HasAvatar bool `json:"hasAvatar"`

	// Secret A secret and unique user identifier. This secret is generated once and never changes. It is used to both authenticate and identify a user, so it should be kept secret.
	Secret UserSecret `json:"secret"`
}

func (response Register200JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RegisterdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response RegisterdefaultJSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Authenticate a user and obtain a session
	// (POST /auth)
	Auth(ctx context.Context, request AuthRequestObject) (AuthResponseObject, error)
	// List all available delivery methods
	// (GET /delivery-methods)
	DeliveryMethods(ctx context.Context, request DeliveryMethodsRequestObject) (DeliveryMethodsResponseObject, error)
	// Clear the user's dosage schedule
	// (DELETE /dosage)
	ClearDosage(ctx context.Context, request ClearDosageRequestObject) (ClearDosageResponseObject, error)
	// Get the user's dosage and optionally their history
	// (GET /dosage)
	Dosage(ctx context.Context, request DosageRequestObject) (DosageResponseObject, error)
	// Set the user's dosage
	// (PUT /dosage)
	SetDosage(ctx context.Context, request SetDosageRequestObject) (SetDosageResponseObject, error)
	// Delete multiple dosages from the user's history
	// (DELETE /dosage/dose)
	ForgetDoses(ctx context.Context, request ForgetDosesRequestObject) (ForgetDosesResponseObject, error)
	// Record a new dosage to the user's history
	// (POST /dosage/dose)
	RecordDose(ctx context.Context, request RecordDoseRequestObject) (RecordDoseResponseObject, error)
	// Update a dosage in the user's history
	// (PUT /dosage/dose)
	EditDose(ctx context.Context, request EditDoseRequestObject) (EditDoseResponseObject, error)
	// Get the current user
	// (GET /me)
	CurrentUser(ctx context.Context, request CurrentUserRequestObject) (CurrentUserResponseObject, error)
	// Get the current user's avatar
	// (GET /me/avatar)
	CurrentUserAvatar(ctx context.Context, request CurrentUserAvatarRequestObject) (CurrentUserAvatarResponseObject, error)
	// Set the current user's avatar
	// (PUT /me/avatar)
	SetCurrentUserAvatar(ctx context.Context, request SetCurrentUserAvatarRequestObject) (SetCurrentUserAvatarResponseObject, error)
	// Get the current user's secret
	// (GET /me/secret)
	CurrentUserSecret(ctx context.Context, request CurrentUserSecretRequestObject) (CurrentUserSecretResponseObject, error)
	// Delete one of the current user's sessions
	// (DELETE /me/sessions)
	DeleteUserSession(ctx context.Context, request DeleteUserSessionRequestObject) (DeleteUserSessionResponseObject, error)
	// List the current user's sessions
	// (GET /me/sessions)
	CurrentUserSessions(ctx context.Context, request CurrentUserSessionsRequestObject) (CurrentUserSessionsResponseObject, error)
	// Get the server's push notification information
	// (GET /notification/push)
	PushInfo(ctx context.Context, request PushInfoRequestObject) (PushInfoResponseObject, error)
	// Unsubscribe from push notifications
	// (DELETE /notification/push/subscription)
	UserUnsubscribePush(ctx context.Context, request UserUnsubscribePushRequestObject) (UserUnsubscribePushResponseObject, error)
	// Get the user's push notification subscription
	// (GET /notification/push/subscription)
	UserPushSubscription(ctx context.Context, request UserPushSubscriptionRequestObject) (UserPushSubscriptionResponseObject, error)
	// Subscribe to push notifications
	// (POST /notification/push/subscription)
	UserSubscribePush(ctx context.Context, request UserSubscribePushRequestObject) (UserSubscribePushResponseObject, error)
	// Register a new account
	// (POST /register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Auth operation middleware
func (sh *strictHandler) Auth(w http.ResponseWriter, r *http.Request, params AuthParams) {
	var request AuthRequestObject

	request.Params = params

	var body AuthJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Auth(ctx, request.(AuthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Auth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthResponseObject); ok {
		if err := validResponse.VisitAuthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeliveryMethods operation middleware
func (sh *strictHandler) DeliveryMethods(w http.ResponseWriter, r *http.Request) {
	var request DeliveryMethodsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeliveryMethods(ctx, request.(DeliveryMethodsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeliveryMethods")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeliveryMethodsResponseObject); ok {
		if err := validResponse.VisitDeliveryMethodsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ClearDosage operation middleware
func (sh *strictHandler) ClearDosage(w http.ResponseWriter, r *http.Request) {
	var request ClearDosageRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ClearDosage(ctx, request.(ClearDosageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ClearDosage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ClearDosageResponseObject); ok {
		if err := validResponse.VisitClearDosageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Dosage operation middleware
func (sh *strictHandler) Dosage(w http.ResponseWriter, r *http.Request, params DosageParams) {
	var request DosageRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Dosage(ctx, request.(DosageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Dosage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DosageResponseObject); ok {
		if err := validResponse.VisitDosageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetDosage operation middleware
func (sh *strictHandler) SetDosage(w http.ResponseWriter, r *http.Request) {
	var request SetDosageRequestObject

	var body SetDosageJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SetDosage(ctx, request.(SetDosageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetDosage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SetDosageResponseObject); ok {
		if err := validResponse.VisitSetDosageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ForgetDoses operation middleware
func (sh *strictHandler) ForgetDoses(w http.ResponseWriter, r *http.Request, params ForgetDosesParams) {
	var request ForgetDosesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ForgetDoses(ctx, request.(ForgetDosesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ForgetDoses")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ForgetDosesResponseObject); ok {
		if err := validResponse.VisitForgetDosesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RecordDose operation middleware
func (sh *strictHandler) RecordDose(w http.ResponseWriter, r *http.Request) {
	var request RecordDoseRequestObject

	var body RecordDoseJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RecordDose(ctx, request.(RecordDoseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RecordDose")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RecordDoseResponseObject); ok {
		if err := validResponse.VisitRecordDoseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EditDose operation middleware
func (sh *strictHandler) EditDose(w http.ResponseWriter, r *http.Request) {
	var request EditDoseRequestObject

	var body EditDoseJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EditDose(ctx, request.(EditDoseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EditDose")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EditDoseResponseObject); ok {
		if err := validResponse.VisitEditDoseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CurrentUser operation middleware
func (sh *strictHandler) CurrentUser(w http.ResponseWriter, r *http.Request) {
	var request CurrentUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CurrentUser(ctx, request.(CurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CurrentUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CurrentUserResponseObject); ok {
		if err := validResponse.VisitCurrentUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CurrentUserAvatar operation middleware
func (sh *strictHandler) CurrentUserAvatar(w http.ResponseWriter, r *http.Request) {
	var request CurrentUserAvatarRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CurrentUserAvatar(ctx, request.(CurrentUserAvatarRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CurrentUserAvatar")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CurrentUserAvatarResponseObject); ok {
		if err := validResponse.VisitCurrentUserAvatarResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetCurrentUserAvatar operation middleware
func (sh *strictHandler) SetCurrentUserAvatar(w http.ResponseWriter, r *http.Request) {
	var request SetCurrentUserAvatarRequestObject

	request.ContentType = r.Header.Get("Content-Type")

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SetCurrentUserAvatar(ctx, request.(SetCurrentUserAvatarRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetCurrentUserAvatar")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SetCurrentUserAvatarResponseObject); ok {
		if err := validResponse.VisitSetCurrentUserAvatarResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CurrentUserSecret operation middleware
func (sh *strictHandler) CurrentUserSecret(w http.ResponseWriter, r *http.Request) {
	var request CurrentUserSecretRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CurrentUserSecret(ctx, request.(CurrentUserSecretRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CurrentUserSecret")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CurrentUserSecretResponseObject); ok {
		if err := validResponse.VisitCurrentUserSecretResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteUserSession operation middleware
func (sh *strictHandler) DeleteUserSession(w http.ResponseWriter, r *http.Request) {
	var request DeleteUserSessionRequestObject

	var body DeleteUserSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteUserSession(ctx, request.(DeleteUserSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteUserSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteUserSessionResponseObject); ok {
		if err := validResponse.VisitDeleteUserSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CurrentUserSessions operation middleware
func (sh *strictHandler) CurrentUserSessions(w http.ResponseWriter, r *http.Request) {
	var request CurrentUserSessionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CurrentUserSessions(ctx, request.(CurrentUserSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CurrentUserSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CurrentUserSessionsResponseObject); ok {
		if err := validResponse.VisitCurrentUserSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PushInfo operation middleware
func (sh *strictHandler) PushInfo(w http.ResponseWriter, r *http.Request) {
	var request PushInfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PushInfo(ctx, request.(PushInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PushInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PushInfoResponseObject); ok {
		if err := validResponse.VisitPushInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UserUnsubscribePush operation middleware
func (sh *strictHandler) UserUnsubscribePush(w http.ResponseWriter, r *http.Request) {
	var request UserUnsubscribePushRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UserUnsubscribePush(ctx, request.(UserUnsubscribePushRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UserUnsubscribePush")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UserUnsubscribePushResponseObject); ok {
		if err := validResponse.VisitUserUnsubscribePushResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UserPushSubscription operation middleware
func (sh *strictHandler) UserPushSubscription(w http.ResponseWriter, r *http.Request) {
	var request UserPushSubscriptionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UserPushSubscription(ctx, request.(UserPushSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UserPushSubscription")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UserPushSubscriptionResponseObject); ok {
		if err := validResponse.VisitUserPushSubscriptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UserSubscribePush operation middleware
func (sh *strictHandler) UserSubscribePush(w http.ResponseWriter, r *http.Request) {
	var request UserSubscribePushRequestObject

	var body UserSubscribePushJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UserSubscribePush(ctx, request.(UserSubscribePushRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UserSubscribePush")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UserSubscribePushResponseObject); ok {
		if err := validResponse.VisitUserSubscribePushResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xb624ctxV+FWJaIEmx2nVkx0D3n2IpjdL4gqxUF7AFgzNzdocRh5yQnFW2wQJ9h75h",
	"n6Q4JOfO2YusTfrP2iEPz+U7V9K/RYnMCylAGB3Nf4sU6EIKDfaPK6Wk+sn/gj8kUhgQBv9Ji4KzhBom",
	"xexnLQX+ppMMcor/+rOCZTSP/jRrqM/cVz2zVKPtdjuJUtCJYgUSiebRTQZEwS8laEOYJkysKWfp9KOI",
	"cK3fjtQvgbM1qM1rMJlM8ZdCyQKUYY5vZn/rEr8gOpPKEG0UEyuioFCgQRj8w2RAUk+T5JbolNxkyIMm",
	"Dxk1ZCUBGTLSru2eT5YMeKqn0SQymwKieeTOiCbRr2dSpaCi+dfbSSRoDkO+UOhlyTnBz0Qug8zsIv18",
	"O4lKwZz5hrTtp8fQPUelozmYgjSaf0CtVid5Ye7q7TL+GRITbSfRpdR0BUObJFIkpVIgkhEliDKPQSGn",
	"oI2SKxCkoCbJQBMpLPexTDeEGiJFAlPyVvANUcBhTYUhbNkXDm1nCbSkZMLAClRbzBcWhn08DdnrUzeS",
	"lBr2Gj2VekTe1CqK0FyWwiCdpVQ5NdE8WnJJTUPYKaZrmokVRa0pDxOvvpIYzAOAwNMsgklKN7pzWirL",
	"mMOu4573kdDTl5eyxdM4ML5n2ki1sV5qINf7goXb9TbWSNgKuK1pU6XopiHdXhSAX577yNWPC/4TobEs",
	"jXMTS2+CoKJis9PGLx8Jn1LDPvc7EXgwXrB0NFj8UgJhKQbGJQNFllJZlchGuZ3jmDAvX+x0MPQCQ+9B",
	"XJjwoYbl0FI7eaCa2A1dmFIDZ7h0l9JeVGe9XS6PPo7I5bIJ+7ITXlANNpj0DamPZ/KbYGAd86lKdSGX",
	"cpl0gPUUDGU8kA8u0pThPyknfk0L9ODSsvdiEYos7zMwGahmuUvTfnnNYCwlByratF7JNIDkC1HvJolM",
	"oUabI/5lqYGD1vbnhDMMDF8NNLudRDnoKun0ndt/Iu73uMr2TtgBqZ5hKroh3f8oE8qDR3L7peVEYT9f",
	"yTP/Y6lBTT291pczlhdSWRS70sEuRDdkCS4sqMmiecRZnMZTLWdwnnCW3IOa+TV6hhusVG8kspKMBMeW",
	"/ijnb5fR/MPuqNwm99pv3t6F6rlK/74AEa2N0364c+oI+uymsCT620GUORpKQc5EauMOTRKMiZ9wqVXT",
	"A8SfilJnn+DXglnt3+3J2ai18WKt+lqJhH9jNaBBpAMZiZF7irce5OzKBtEtZu56Znw9Bvp9aq9DXAqK",
	"rSElSyXzAOeo87g0JKGCxEDkGpRiaQqCxJtacpRuFExHw2FnNjTM8DF84KejiX49UL49odE+qvxdqbNr",
	"sZShg50aFZhSCUgrtaD3gSJUpAT7JcoEBkmXI6xisaHAhS6kkQdZ8pQIAFtU6jK2kQrwD8RtRx491Her",
	"EVvYk/8Om1BY+pZqePniDARG2rTqg6QiF1hGfVsul6AqhvELFeTq1eXigrw7O//mJSnKmLOE3MOmEcCy",
	"58V9YJwjIpBtWpoMg19CDZCNLBVpMek3TMn1kugCEgyR6YRQzit0aIfIkY0kL7VxJ2VA/nHx7vqyfaBd",
	"iGEKJtYETCS8TIFQ8sP7G6LZCi31wEzmTCCV63hTFLlQbI0s38PGewmKe70gb97eONOi31+9uvy+0cNG",
	"lpXYIBK1KXwJSQ2dku+kIrlU0Lb/hGgA8jG61Xik49/y8x5iBNvHqFNSxBsDgUTlkblwaCmquD50jUSK",
	"JVuVymkGMykdwqpCnd04/SgqaLvKD1OeE7aH9oRyjkL0OZka+cPi7Zsvv5qS1z3pq2iylKVICTVzkhlT",
	"6PlslsIaOAJ7mst/Mc7pVKrVDMTZ7WKWykTP3kM8u3h3PeufNnOnDRwDRFpIJkbKwOrro0M3ZgqbUuzq",
	"G5bDjnqTCZIzzpmGRIpUYxf7kLHEgbCtfGJJgm6itKloPGQghuut38WALiBRxWiTDVapYJqQFCv54IP1",
	"EX0fBt172IwMFhxy8Xsf+wN4BYJWibVLoB7sezIkCsyEUF1VcIAuTXzyI1fu2Ara7yG2YNybS4rzb16m",
	"YQ6uOMc/E5KUag3kki2XDP777/98D5znVLQDoZ9LuADpln/p/WRiv7y5XtygDHic+ppAh/RXaGMgCnTJ",
	"7RgKSTKNgbcUWHQp0BpS4mDKBLl4s7gm//zr9OU5cVY8Lrt5mSdO+YOadldVUruSBwQmxgVoHYw6F0S7",
	"Tz7ahMuERAE1kO7t0ipa2Kb5PUd3XOeVq4I++Dy/foIZUpScE7YkzBABmIL8x0f1p2O9d3Vw0zcc32dz",
	"qs2thpET8GtYsaV+hFafB/vYxq4tdkIN1C32JgHw2Hral3J6ow3kQ/BkVF+sqaFqd49qSWXUuhS166fD",
	"LrU3GuF1X7erAfLd2s6pLp7+hbZz3aP81G/gVUPYCDumxoWNkmFPxC+2EPKzHauTVm/q8oxfxzRZgQCF",
	"FrRjVrvTYT7JqFhhYrq26xAyGPhjabJuwWerLnfAxrv/hGiJ3qMzW+vGWGIVxp96UHvsRTxJe7ydRBqS",
	"UjGzWdjK0WIsBqpAXfhE5UpKhI39uWEZyxdHg/kuwfcpUX0gaZhag3JBM3qGxpMFCFqwaB49nz6bPvNc",
	"2+NnVYospLZCIv5tUrxO0bT4FZcrmoMBpW3PHgYhoSvsM7xP+a4jp/fVMMTfuUztBBdFAup6aa9XhNjZ",
	"BdKIJq07nn5JeudgDNp8K9PNUddFXe/WNZx3uWAL+H0P8gSG7rJ1K1tXXOfPnn0Gp0beg9gdzt2SfZMm",
	"tyrEcH+osiiTBLRelljmcbla2YJoGtmFS1ryUcXVcs+693pt/EfzD3eTSJd5TtXGw6xxbI8mkRIZY5tI",
	"aCWmHVSuEITWC6M7JDqrZppnflaKnK0ggObuhRrm1c8y0mE3C92B6+BaYY/qFRjFYA1pYCJ8Glv8yLSx",
	"bTJdU8ZpzAe3CrplBjfdrgwhm5EMNgZDC7ziQJW/uxto/8UQ4h1dJLgZ0tZU/bN1UEttGauz+Re6Gtuj",
	"GdPSNTB9kScjKKvE60VNG/R+KUFtmpiXuXuqhaGqG/UCno5rsOGvJ1B+M6bHCib2MsmHR3fzc0Cxtd1O",
	"dnJ3JdI9vGFjexrO7p40kDYAPWwA7U0Znjl7oLjrZtMHTNNZV2V9p1QUst6Apcl2Uin7WOaqm86dPPqj",
	"KrM8MJMx0U7K6FVYsSssvuzMDJitb9sAxR6lgQShyk4ySKHkmqWQYi/KdD0pQLGnNhceGuF6d6JOMR0v",
	"/RuYgI/aTFG4GyduJxGsZjTst0UZ8NsFmFZkelyFcQiYQtXBvtCnwZwk7C1CCt0d3mfNdXE4xn8n1cqq",
	"0nauBwRBJPiJ+XxcFStGlTAJJdvgLTWQ68v6+UnrEtkOjRyjh9wnD7Pz3dGmqmZiTlv66Wx1aQmTvOSG",
	"FbzCgm7uVbwRdyM/WOb/BIlU6aW7Cn6a6vqkd/GDunb09vrzS/Ejn43sjXao6Roe/QDnDEEoEfBQKce/",
	"BjvIuqG4dpUy85mmPSYhdbQRTkpFShsP6bz5sKPK60t3+ZLblxBUEPiVaTu67DwPeVQg7Z79dM55a+kS",
	"Wgnl0+t+o2FgdaOdYDH5ylUXdop1QiDf1iOKgzN1Vfe4uetT6bHK8G3q4a4vhxmth3P7dOcnW3s1yHLM",
	"cH/pKq65JGOCOisOr8kO1puHRDUoPKXi6mOGGhyvgcJaG4sbj1XY40ugE+lvcZz+PAKbGdI+BNaTxSds",
	"Z045wToe0dWY9cSI1pUixyxiJ0V6V4XqKimnl2qu9DRVz+G3Lk1hekhdOrwCOazUObRY7ZjRKfDJC1cp",
	"6vnAwKTeZoEwtd+v6r2nH+ZVcHn8FO+kiraju6P0i07TvkKfFaXORsNZ/UjphJVIfcZxOnWPdr7QgUcn",
	"rWchp5qZVqHqMC5aZmgvGTPHTA9e34TDGrrDrahfdqEmjx+ylg0B/2Qv9DpsO4lehEjddGdchrSIjTw0",
	"e7IKvGF8jO9xxY/EGdTo4P3Tk6bwg5/2/HFPeQa56FHRbs9jsP9HRPWmjbsl2IWt8NDFZq+Bsz793HEA",
	"4MeV37+b2he7n6bujp4KVkwb9+RjbNblVzxVzTf+NMO+37Z3IO5IO3jfO8wa+T9vnz/JOmyK40YBk9+v",
	"17j7w6+fK0j4uZt/2x+olro0uo83PtxtkaitANysu1Tcv9zQ81nzMGRKi2JGC2aV7Na4P++2/wsAAP//",
	"2tj2ECc7AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
