//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version (devel) DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	"libdb.so/e2clicker/services/user"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	// Details Additional details about the error
	Details *interface{} `json:"details,omitempty"`

	// Internal Whether the error is internal
	Internal *bool `json:"internal,omitempty"`

	// InternalCode An internal code for the error (useless for clients)
	InternalCode *string `json:"internalCode,omitempty"`

	// Message A message describing the error
	Message string `json:"message"`
}

// Locale A locale identifier.
type Locale = user.Locale

// Session A session for a user.
type Session struct {
	// ID The session identifier
	ID int64 `json:"id"`

	// CreatedAt The time the session was created
	CreatedAt time.Time `json:"created_at"`

	// LastUsed The last time the session was used
	LastUsed time.Time `json:"last_used"`

	// ExpiresAt The time the session expires, or null if it never expires
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
}

// User A user of the system.
type User struct {
	// Name The user's name
	Name string `json:"name"`

	// Locale A locale identifier.
	Locale Locale `json:"locale"`

	// HasAvatar Whether the user has an avatar.
	HasAvatar bool `json:"has_avatar"`
}

// UserSecret A secret and unique user identifier. This secret is generated once and never changes. It is used to both authenticate and identify a user, so it should be kept secret.
type UserSecret = user.Secret

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = Error

// AuthJSONBody defines parameters for Auth.
type AuthJSONBody struct {
	// Secret A secret and unique user identifier. This secret is generated once and never changes. It is used to both authenticate and identify a user, so it should be kept secret.
	Secret UserSecret `json:"secret"`
}

// AuthParams defines parameters for Auth.
type AuthParams struct {
	// UserAgent The user agent of the client making the request.
	UserAgent *string `json:"User-Agent,omitempty"`
}

// DeleteUserSessionJSONBody defines parameters for DeleteUserSession.
type DeleteUserSessionJSONBody struct {
	// ID The session identifier to delete
	ID int64 `json:"id"`
}

// RegisterJSONBody defines parameters for Register.
type RegisterJSONBody struct {
	// Name The name to register with
	Name string `json:"name"`
}

// AuthJSONRequestBody defines body for Auth for application/json ContentType.
type AuthJSONRequestBody AuthJSONBody

// DeleteUserSessionJSONRequestBody defines body for DeleteUserSession for application/json ContentType.
type DeleteUserSessionJSONRequestBody DeleteUserSessionJSONBody

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody RegisterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate a user and obtain a session
	// (POST /auth)
	Auth(w http.ResponseWriter, r *http.Request, params AuthParams)
	// Get the current user
	// (GET /me)
	CurrentUser(w http.ResponseWriter, r *http.Request)
	// Get the current user's avatar
	// (GET /me/avatar)
	CurrentUserAvatar(w http.ResponseWriter, r *http.Request)
	// Set the current user's avatar
	// (POST /me/avatar)
	SetCurrentUserAvatar(w http.ResponseWriter, r *http.Request)
	// Get the current user's secret
	// (GET /me/secret)
	CurrentUserSecret(w http.ResponseWriter, r *http.Request)
	// Delete one of the current user's sessions
	// (DELETE /me/sessions)
	DeleteUserSession(w http.ResponseWriter, r *http.Request)
	// List the current user's sessions
	// (GET /me/sessions)
	CurrentUserSessions(w http.ResponseWriter, r *http.Request)
	// Register a new account
	// (POST /register)
	Register(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Auth operation middleware
func (siw *ServerInterfaceWrapper) Auth(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AuthParams

	headers := r.Header

	// ------------- Optional header parameter "User-Agent" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("User-Agent")]; found {
		var UserAgent string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "User-Agent", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "User-Agent", valueList[0], &UserAgent, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "User-Agent", Err: err})
			return
		}

		params.UserAgent = &UserAgent

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Auth(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CurrentUser operation middleware
func (siw *ServerInterfaceWrapper) CurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CurrentUserAvatar operation middleware
func (siw *ServerInterfaceWrapper) CurrentUserAvatar(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CurrentUserAvatar(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetCurrentUserAvatar operation middleware
func (siw *ServerInterfaceWrapper) SetCurrentUserAvatar(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetCurrentUserAvatar(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CurrentUserSecret operation middleware
func (siw *ServerInterfaceWrapper) CurrentUserSecret(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CurrentUserSecret(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUserSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUserSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CurrentUserSessions operation middleware
func (siw *ServerInterfaceWrapper) CurrentUserSessions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CurrentUserSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/auth", wrapper.Auth)
	m.HandleFunc("GET "+options.BaseURL+"/me", wrapper.CurrentUser)
	m.HandleFunc("GET "+options.BaseURL+"/me/avatar", wrapper.CurrentUserAvatar)
	m.HandleFunc("POST "+options.BaseURL+"/me/avatar", wrapper.SetCurrentUserAvatar)
	m.HandleFunc("GET "+options.BaseURL+"/me/secret", wrapper.CurrentUserSecret)
	m.HandleFunc("DELETE "+options.BaseURL+"/me/sessions", wrapper.DeleteUserSession)
	m.HandleFunc("GET "+options.BaseURL+"/me/sessions", wrapper.CurrentUserSessions)
	m.HandleFunc("POST "+options.BaseURL+"/register", wrapper.Register)

	return m
}

type ErrorResponseJSONResponse Error

type AuthRequestObject struct {
	Params AuthParams
	Body   *AuthJSONRequestBody
}

type AuthResponseObject interface {
	VisitAuthResponse(w http.ResponseWriter) error
}

type Auth200JSONResponse struct {
	// Token The session token
	Token string `json:"token"`
}

func (response Auth200JSONResponse) VisitAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AuthdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response AuthdefaultJSONResponse) VisitAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CurrentUserRequestObject struct {
}

type CurrentUserResponseObject interface {
	VisitCurrentUserResponse(w http.ResponseWriter) error
}

type CurrentUser200JSONResponse User

func (response CurrentUser200JSONResponse) VisitCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CurrentUserdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CurrentUserdefaultJSONResponse) VisitCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CurrentUserAvatarRequestObject struct {
}

type CurrentUserAvatarResponseObject interface {
	VisitCurrentUserAvatarResponse(w http.ResponseWriter) error
}

type CurrentUserAvatar200ImageResponse struct {
	Body          io.Reader
	ContentType   string
	ContentLength int64
}

func (response CurrentUserAvatar200ImageResponse) VisitCurrentUserAvatarResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", response.ContentType)
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type CurrentUserAvatardefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CurrentUserAvatardefaultJSONResponse) VisitCurrentUserAvatarResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type SetCurrentUserAvatarRequestObject struct {
	ContentType string
	Body        io.Reader
}

type SetCurrentUserAvatarResponseObject interface {
	VisitSetCurrentUserAvatarResponse(w http.ResponseWriter) error
}

type SetCurrentUserAvatar204Response struct {
}

func (response SetCurrentUserAvatar204Response) VisitSetCurrentUserAvatarResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SetCurrentUserAvatardefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SetCurrentUserAvatardefaultJSONResponse) VisitSetCurrentUserAvatarResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CurrentUserSecretRequestObject struct {
}

type CurrentUserSecretResponseObject interface {
	VisitCurrentUserSecretResponse(w http.ResponseWriter) error
}

type CurrentUserSecret200JSONResponse struct {
	// Secret A secret and unique user identifier. This secret is generated once and never changes. It is used to both authenticate and identify a user, so it should be kept secret.
	Secret UserSecret `json:"secret"`
}

func (response CurrentUserSecret200JSONResponse) VisitCurrentUserSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CurrentUserSecretdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CurrentUserSecretdefaultJSONResponse) VisitCurrentUserSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteUserSessionRequestObject struct {
	Body *DeleteUserSessionJSONRequestBody
}

type DeleteUserSessionResponseObject interface {
	VisitDeleteUserSessionResponse(w http.ResponseWriter) error
}

type DeleteUserSession204Response struct {
}

func (response DeleteUserSession204Response) VisitDeleteUserSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteUserSessiondefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteUserSessiondefaultJSONResponse) VisitDeleteUserSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CurrentUserSessionsRequestObject struct {
}

type CurrentUserSessionsResponseObject interface {
	VisitCurrentUserSessionsResponse(w http.ResponseWriter) error
}

type CurrentUserSessions200JSONResponse []Session

func (response CurrentUserSessions200JSONResponse) VisitCurrentUserSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CurrentUserSessionsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CurrentUserSessionsdefaultJSONResponse) VisitCurrentUserSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register200JSONResponse struct {
	// Name The user's name
	Name string `json:"name"`

	// Locale A locale identifier.
	Locale Locale `json:"locale"`

	// HasAvatar Whether the user has an avatar.
	HasAvatar bool `json:"has_avatar"`

	// Secret A secret and unique user identifier. This secret is generated once and never changes. It is used to both authenticate and identify a user, so it should be kept secret.
	Secret UserSecret `json:"secret"`
}

func (response Register200JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RegisterdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response RegisterdefaultJSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Authenticate a user and obtain a session
	// (POST /auth)
	Auth(ctx context.Context, request AuthRequestObject) (AuthResponseObject, error)
	// Get the current user
	// (GET /me)
	CurrentUser(ctx context.Context, request CurrentUserRequestObject) (CurrentUserResponseObject, error)
	// Get the current user's avatar
	// (GET /me/avatar)
	CurrentUserAvatar(ctx context.Context, request CurrentUserAvatarRequestObject) (CurrentUserAvatarResponseObject, error)
	// Set the current user's avatar
	// (POST /me/avatar)
	SetCurrentUserAvatar(ctx context.Context, request SetCurrentUserAvatarRequestObject) (SetCurrentUserAvatarResponseObject, error)
	// Get the current user's secret
	// (GET /me/secret)
	CurrentUserSecret(ctx context.Context, request CurrentUserSecretRequestObject) (CurrentUserSecretResponseObject, error)
	// Delete one of the current user's sessions
	// (DELETE /me/sessions)
	DeleteUserSession(ctx context.Context, request DeleteUserSessionRequestObject) (DeleteUserSessionResponseObject, error)
	// List the current user's sessions
	// (GET /me/sessions)
	CurrentUserSessions(ctx context.Context, request CurrentUserSessionsRequestObject) (CurrentUserSessionsResponseObject, error)
	// Register a new account
	// (POST /register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Auth operation middleware
func (sh *strictHandler) Auth(w http.ResponseWriter, r *http.Request, params AuthParams) {
	var request AuthRequestObject

	request.Params = params

	var body AuthJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Auth(ctx, request.(AuthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Auth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthResponseObject); ok {
		if err := validResponse.VisitAuthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CurrentUser operation middleware
func (sh *strictHandler) CurrentUser(w http.ResponseWriter, r *http.Request) {
	var request CurrentUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CurrentUser(ctx, request.(CurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CurrentUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CurrentUserResponseObject); ok {
		if err := validResponse.VisitCurrentUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CurrentUserAvatar operation middleware
func (sh *strictHandler) CurrentUserAvatar(w http.ResponseWriter, r *http.Request) {
	var request CurrentUserAvatarRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CurrentUserAvatar(ctx, request.(CurrentUserAvatarRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CurrentUserAvatar")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CurrentUserAvatarResponseObject); ok {
		if err := validResponse.VisitCurrentUserAvatarResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetCurrentUserAvatar operation middleware
func (sh *strictHandler) SetCurrentUserAvatar(w http.ResponseWriter, r *http.Request) {
	var request SetCurrentUserAvatarRequestObject

	request.ContentType = r.Header.Get("Content-Type")

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SetCurrentUserAvatar(ctx, request.(SetCurrentUserAvatarRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetCurrentUserAvatar")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SetCurrentUserAvatarResponseObject); ok {
		if err := validResponse.VisitSetCurrentUserAvatarResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CurrentUserSecret operation middleware
func (sh *strictHandler) CurrentUserSecret(w http.ResponseWriter, r *http.Request) {
	var request CurrentUserSecretRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CurrentUserSecret(ctx, request.(CurrentUserSecretRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CurrentUserSecret")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CurrentUserSecretResponseObject); ok {
		if err := validResponse.VisitCurrentUserSecretResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteUserSession operation middleware
func (sh *strictHandler) DeleteUserSession(w http.ResponseWriter, r *http.Request) {
	var request DeleteUserSessionRequestObject

	var body DeleteUserSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteUserSession(ctx, request.(DeleteUserSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteUserSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteUserSessionResponseObject); ok {
		if err := validResponse.VisitDeleteUserSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CurrentUserSessions operation middleware
func (sh *strictHandler) CurrentUserSessions(w http.ResponseWriter, r *http.Request) {
	var request CurrentUserSessionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CurrentUserSessions(ctx, request.(CurrentUserSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CurrentUserSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CurrentUserSessionsResponseObject); ok {
		if err := validResponse.VisitCurrentUserSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RXS4/bNhD+KwRboA9orc0DPfi2TYsiQIACcYoetkZAS2OJWYpUyJE3RqD/XgxJybIl",
	"27vZdXuTyOHM8JtvHvzKM1PVRoNGx+dfuQVXG+3A//xurbHv4wotZEYjaKRPUddKZgKl0eknZzStuayE",
	"StDX9xbWfM6/S3fa07DrUq+Vt22b8BxcZmVNSvicfyiBWfjcgEMmHZN6I5TMZ/9oTrLxeO8XfdTW1GBR",
	"BndzQCFV/BwqvslzSZ9CsSjDxMo0yLAEBsGdhEuNYLVQ4/N/l4Al2J14cC+KJxy3NfA5XxmjQOihrjcm",
	"hwl/dH+aZSYHtjZD5T82DhQ455czJQm9n3ZmHFqpC7JSgXOimDLA4hYL6yupi8FlR6rahBPw0kLO57e9",
	"3mUvaFafIEOy+c5kQk2aVH6HyRw0yrUEOxsZSviXq8JcxcXGgZ1FfYOdK1nVxnqSaVF1gg7sRmYkWAss",
	"+ZwrucpXM2dSeJkpmd2BTaOMS+mAv9UCnJOBnIfuurDlQRbM+0LK9xiVWRAI+UeBYw3EVpQVeFw7ZffC",
	"sXiIJ3xtbEVHeS4Qrkh4EhFjc7B8/rJNOHyppQX3cIPxQMKMZbpRisk1k8g0bMB2m4/25DUxOJ/2oDO8",
	"C/NQvdT4y+udamJ54SV63S/ahCvh8GPj4IgJ2p6G1p957G1eHdJbko5BaIcOTVH+L2LTBIOIM8ysg5db",
	"h1CNGVQK91FsBAp7uqx4XaVwTGgW5GfjwrJ3qYSrPhVPlduYYG0Ss2kKcbL+g2Ne4ASSLw6RjAdUl8OD",
	"2x4DcgGZBZxOSNphQues0fJzE0EZ1BP2oZSuk5OOFaDBUhSZ0Rn4k4H4WSl0AW7G3no5iixDw1YGSyYa",
	"LEljJjAciQa2sQokzBlKIVeaRuVsBewOaoxWH1TS4hUvUtKoEULWWInbBQU4sGwFwoK9aUhLbMOeN355",
	"53KJWAcdUq8NiaJEYhDvDbKdUxuwoXbyawqeqUGLWvI5fzW7nl1Hr735VETLtXH+kpQBfjR4m1NoaZfE",
	"ragAwTo+vz3GQiYK0NhlVWh+rBJ3XQOL8wHFQdK5EkTurxhxJYpd3ZAOngzmkcN+tww8Boe/mnz7qNFm",
	"P79dT+dTOTgg/mEKRQXjdGmD5GAce3l9/QRP0dyBPl3Tg8i56SBITTl8ONAtmiwD59aNUlumTFFAzqSe",
	"cS+4Fo06Clx/73R/Bh3yn89vlwl3TVUJu4002yV2ZJPOmVmhkJqJ7ppeSRpKYQETfH3TWAsafdl/YgjO",
	"keIsahbQSthQ/aJ8CJ7FaeWJMPbA/QE40t6BlO6a1zmsboLkWcRkJQpIf94Hqm/pK6nJqzEJH4NT7Gdd",
	"I70kUL0ZsjJd/xaA0zAdK0DfitC4YLweJ/webC7e6EKALU4DFim2q6HnKNZ31mesi5es4I+nbDdmXJiy",
	"bneVEAFfGePTWQHCOAy/+fWAQ6ijz9VDH/7UoCEu+nf+0TEx9j+sy55LmuDBQdgCgM8XuAA3Mxr6Yegw",
	"hDFmbfKAvImyT8wciVC5c6nS0aPtwRbWiu235sNzA/tOOjyNJyWFhUI6DO++6ar+vpN4rjQ4/jyjHaJ+",
	"5xS7l36iPj2neX2XmCuFUn+u/Qx/frxJ/rtyu/zfJ9COEkwwDfdMZJlpNO6/2jxuw/fa7ZJeI/Ts6l5G",
	"jVV8zlN6bLXL9t8AAAD//7EXK6iiFQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
