// Code generated by nixmod2go. DO NOT EDIT.
package e2clickermodule

import (
	"encoding/json"
	"errors"
)

// BackendConfig is the struct type for `config`.
type BackendConfig struct {
	// Enable: whether to enable e2clicker backend.
	Enable  bool   `json:"enable"`
	Package string `json:"package"`
	// API: configuration for the API server.
	API API `json:"api"`
	// Debug: enable debug logging and other debug features.
	Debug bool `json:"debug"`
	// LogFormat: format of the log output.
	LogFormat LogFormat `json:"logFormat"`
	// Notification: configuration for the notification service.
	Notification Notification `json:"notification"`
	// PostgreSQL: configuration for the PostgreSQL database.
	PostgreSQL PostgreSQL `json:"postgresql"`
}

// PostgreSQL is the struct type for `config.postgresql`.
type PostgreSQL struct {
	// DatabaseURI: URI of the database to use.
	DatabaseURI string `json:"databaseURI"`
}

// Notification is the struct type for `config.notification`.
type Notification struct {
	// ClientTimeout: HTTP timeout when making requests to notification servers.
	ClientTimeout string `json:"clientTimeout"`
	// WebPush: path to the file containing the VAPID keys encoded in JSON.
	WebPush WebPush `json:"webPush"`
}

// WebPush is the struct type for `config.notification.webPush`.
type WebPush struct {
	// Enable: whether to enable VAPID-encrypted Web Push notifications support.
	Enable bool `json:"enable"`
	// VAPIDKeys: VAPID keys to use for sending notifications.
	VAPIDKeys VAPIDKeysJSON `json:"vapidKeys"`
}

// API is the struct type for `config.api`.
type API struct {
	// ListenAddress address the API server should listen on.
	ListenAddress string `json:"listenAddress"`
}

// LogFormat is the enum type for `config.logFormat`.
type LogFormat string

const (
	LogFormatColor LogFormat = "color"
	LogFormatJSON  LogFormat = "json"
	LogFormatText  LogFormat = "text"
)

// VAPIDKeys describes the `either` type for `config.notification.webPush.vapidKeys`.
type VAPIDKeys interface {
	isVAPIDKeys()
}

// VAPIDKeysPath is one of the types that satisfy [VAPIDKeys].
type VAPIDKeysPath string

// VAPIDKeysSubmodule is one of the types that satisfy [VAPIDKeys].
type VAPIDKeysSubmodule struct {
	// PrivateKey: VAPID private key.
	PrivateKey string `json:"privateKey"`
	// PublicKey: VAPID public key.
	PublicKey string `json:"publicKey"`
}

func (v VAPIDKeysPath) isVAPIDKeys() {
}
func (v VAPIDKeysSubmodule) isVAPIDKeys() {
}

// NewVAPIDKeysPath constructs a value of type `path` that satisfies [VAPIDKeys].
func NewVAPIDKeysPath(v string) VAPIDKeys {
	return VAPIDKeysPath(v)
}

// NewVAPIDKeysSubmodule constructs a value of type `submodule` that satisfies [VAPIDKeys].
func NewVAPIDKeysSubmodule(v struct {
	// PrivateKey: VAPID private key.
	PrivateKey string `json:"privateKey"`
	// PublicKey: VAPID public key.
	PublicKey string `json:"publicKey"`
}) VAPIDKeys {
	return VAPIDKeysSubmodule(v)
}

// VAPIDKeysJSON wraps [VAPIDKeys] and implements the json.Unmarshaler interface.
type VAPIDKeysJSON struct{ Value VAPIDKeys }

// UnmarshalJSON implements the [json.Unmarshaler] interface for [VAPIDKeys].
func (v *VAPIDKeysJSON) UnmarshalJSON(data []byte) error {
	_v, err := unmarshalVAPIDKeys(data)
	if err != nil {
		return err
	}
	v.Value = _v
	return nil
}

// MarshalJSON implements the [json.Marshaler] interface for [VAPIDKeys].
func (v VAPIDKeysJSON) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Value)
}

func unmarshalVAPIDKeys(data json.RawMessage) (VAPIDKeys, error) {

	var v0 string
	if err := json.Unmarshal(data, &v0); err == nil {
		return VAPIDKeysPath(v0), nil
	}

	var v1 struct {
		// PrivateKey: VAPID private key.
		PrivateKey string `json:"privateKey"`
		// PublicKey: VAPID public key.
		PublicKey string `json:"publicKey"`
	}
	if err := json.Unmarshal(data, &v1); err == nil {
		return VAPIDKeysSubmodule(v1), nil
	}

	return nil, errors.New("failed to unmarshal VAPIDKeys: unknown type received")
}
