// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgresql

import (
	"github.com/jackc/pgx/v5/pgtype"
	xid "github.com/rs/xid"
	notification "libdb.so/hrtclicker/v2/services/notification"
)

type DeliveryMethod struct {
	ID    string
	Units string
	Name  string
}

type DosageHistory struct {
	DoseID         int64
	LastDose       pgtype.Int8
	UserID         pgtype.Uint32
	DeliveryMethod pgtype.Text
	Dose           pgtype.Numeric
	TakenAt        pgtype.Timestamptz
	TakenOffAt     pgtype.Timestamptz
}

type DosageSchedule struct {
	UserID         xid.ID
	DeliveryMethod pgtype.Text
	Dose           pgtype.Numeric
	Interval       pgtype.Interval
	Concurrence    pgtype.Numeric
}

type Meta struct {
	V int16
}

type NotificationHistory struct {
	NotificationID int64
	UserID         pgtype.Uint32
	DosageID       pgtype.Int8
	SentAt         pgtype.Timestamptz
	ErrorReason    pgtype.Text
}

type User struct {
	UserID              xid.ID
	Email               string
	Passhash            []byte
	Name                string
	NotificationService notification.NotificationConfigJSON
	NotificationMessage pgtype.Text
}

type UserAvatar struct {
	UserID      xid.ID
	AvatarImage []byte
}

type UserSession struct {
	SessionID int64
	UserID    xid.ID
	Token     []byte
	CreatedAt pgtype.Timestamp
	LastUsed  pgtype.Timestamp
	UserAgent pgtype.Text
}
