name: Test

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run local tests
        run: just test
        shell: nix develop -c bash -e {0}

      - name: Run Flake tests
        run: nix flake check path:"$PWD"
